'use strict';

module.exports = {
  id: 'crystal-academy',
  title: '晶核學院綜合題庫',
  questions: [
    { question: '48 ÷ 6 等於多少？', choices: ['6', '7', '8', '9'], correctIndex: 2 },
    { question: '125 + 275 等於多少？', choices: ['300', '350', '400', '450'], correctIndex: 2 },
    { question: '9 × 7 等於多少？', choices: ['56', '63', '72', '79'], correctIndex: 1 },
    { question: '一小時有多少分鐘？', choices: ['30', '45', '60', '90'], correctIndex: 2 },
    { question: '3/4 可寫成哪一個小數？', choices: ['0.25', '0.5', '0.75', '1.25'], correctIndex: 2 },
    { question: '長方形長 8 cm、闊 5 cm，面積是多少？', choices: ['13 cm²', '26 cm²', '40 cm²', '80 cm²'], correctIndex: 2 },
    { question: '1 公里等於多少米？', choices: ['10', '100', '1,000', '10,000'], correctIndex: 2 },
    { question: '2、5、8、11 的下一個數是？', choices: ['12', '13', '14', '15'], correctIndex: 2 },
    { question: '「一心一意」是哪一類詞語？', choices: ['成語', '動詞', '量詞', '擬聲詞'], correctIndex: 0 },
    { question: '「明亮」的反義詞是？', choices: ['光滑', '黑暗', '溫暖', '清楚'], correctIndex: 1 },
    { question: '下列哪一個量詞適合「船」？', choices: ['艘', '本', '棵', '枚'], correctIndex: 0 },
    { question: '「他跑得很快」中的「快」形容甚麼？', choices: ['人物', '動作', '地方', '時間'], correctIndex: 1 },
    { question: 'Apple 的中文意思是？', choices: ['橙', '蘋果', '提子', '梨'], correctIndex: 1 },
    { question: '哪一個英文單字表示「圖書館」？', choices: ['laboratory', 'library', 'bakery', 'hospital'], correctIndex: 1 },
    { question: 'She ___ to school every day.', choices: ['go', 'goes', 'going', 'gone'], correctIndex: 1 },
    { question: '「child」的複數是？', choices: ['childs', 'childes', 'children', 'childrens'], correctIndex: 2 },
    { question: '植物進行光合作用時會吸收哪種氣體？', choices: ['氧氣', '二氧化碳', '氫氣', '氦氣'], correctIndex: 1 },
    { question: '水的沸點在標準氣壓下是多少？', choices: ['0°C', '50°C', '100°C', '150°C'], correctIndex: 2 },
    { question: '人體用哪個器官呼吸？', choices: ['胃', '肺', '腎', '肝'], correctIndex: 1 },
    { question: '地球繞太陽一周大約需時多久？', choices: ['一天', '一個月', '一年', '十年'], correctIndex: 2 },
    { question: '哪一種能源屬於可再生能源？', choices: ['煤', '石油', '太陽能', '天然氣'], correctIndex: 2 },
    { question: '磁鐵通常會吸引哪一種物料？', choices: ['木', '玻璃', '鐵', '塑膠'], correctIndex: 2 },
    { question: '香港位於中國的哪一方？', choices: ['東北方', '東南方', '西北方', '正北方'], correctIndex: 1 },
    { question: '世界上面積最大的海洋是？', choices: ['大西洋', '印度洋', '北冰洋', '太平洋'], correctIndex: 3 },
    { question: '地圖上的 N 通常代表哪個方向？', choices: ['東', '南', '西', '北'], correctIndex: 3 },
    { question: '一星期有多少天？', choices: ['5', '6', '7', '8'], correctIndex: 2 },
    { question: '96 減去 39 等於多少？', choices: ['47', '57', '63', '67'], correctIndex: 1 },
    { question: '下列哪個數是質數？', choices: ['9', '15', '17', '21'], correctIndex: 2 },
    { question: '圓形有多少條直邊？', choices: ['0', '1', '2', '4'], correctIndex: 0 },
    { question: '0.6 與 0.06，哪一個較大？', choices: ['0.6', '0.06', '一樣大', '不能比較'], correctIndex: 0 },
    { question: '「守株待兔」提醒我們不要怎樣？', choices: ['勤力工作', '只靠僥倖', '幫助別人', '珍惜時間'], correctIndex: 1 },
    { question: '哪一句使用了問號？', choices: ['今天真熱', '你吃飯了嗎', '請安靜', '小心'], correctIndex: 1 },
    { question: 'The opposite of “hot” is ___.', choices: ['cold', 'high', 'fast', 'dry'], correctIndex: 0 },
    { question: 'Which word is a colour?', choices: ['table', 'purple', 'jump', 'music'], correctIndex: 1 },
    { question: '聲音不能在哪一種環境中傳播？', choices: ['空氣', '水', '鋼鐵', '真空'], correctIndex: 3 },
    { question: '月亮本身會發光嗎？', choices: ['會，永遠發光', '不會，反射陽光', '只在晚上發光', '只在滿月發光'], correctIndex: 1 },
    { question: '哪種動物屬於哺乳類？', choices: ['海豚', '鯊魚', '八爪魚', '企鵝'], correctIndex: 0 },
    { question: '食物鏈中的生產者通常是？', choices: ['植物', '獅子', '人類', '真菌'], correctIndex: 0 },
    { question: '香港的法定貨幣是？', choices: ['人民幣', '港元', '日圓', '美元'], correctIndex: 1 },
    { question: '赤道把地球分成哪兩個半球？', choices: ['東西半球', '南北半球', '海陸半球', '冷熱半球'], correctIndex: 1 },
  ],
};
