// Authoring catalogue for the twenty-chapter campaign. Combat consumes the
// encounter definitions; the story and asset build consume the same identities.
const l=(zh,en)=>({'zh-HK':zh,'en-US':en});
export const ADVENTURE_ACTS=[
  l('第一幕 · 破曉之約','Act I · The Promise at Dawn'),
  l('第二幕 · 潮聲與舊信','Act II · Tides and Old Letters'),
  l('第三幕 · 火與霜的答案','Act III · Answers in Fire and Frost'),
  l('第四幕 · 願望的代價','Act IV · The Price of a Wish'),
  l('第五幕 · 一起回答','Act V · An Answer Together'),
];
export const ADVENTURE_MINIONS={
  'paper-sentry':{name:l('紙甲衛兵','Paper Sentry'),brain:'shield',element:'physical',hp:78,damage:8,speed:85,range:90,art:'A small folded cream paper crane automaton, scarlet wax-seal shield, brass letter-opener spear, origami joints, vigilant curious face'},
  'reed-frog':{name:l('雨葉蛙','Reed Frog'),brain:'thrower',element:'nature',hp:42,damage:6,speed:100,range:460,art:'A round moss-green tree frog with a lily-pad hood, seed-pod blowpipe, tiny turquoise cheeks, raindrops on leaf cloak'},
  'tide-crab':{name:l('潮甲蟹','Tide Crab'),brain:'shield',element:'water',hp:94,damage:9,speed:85,range:100,art:'A rounded turquoise hermit crab, pearlescent seashell shield, one broad coral claw, sandy feet, warm amber eyes'},
  'bubble-jelly':{name:l('泡泡水母','Bubble Jelly'),brain:'thrower',element:'water',hp:40,damage:6,speed:115,range:490,art:'A floating blue jellyfish with a translucent bell, bright mint inner core, four ribbon tentacles, tiny book-shaped satchel'},
  'ember-salamander':{name:l('煤火蠑螈','Ember Salamander'),brain:'slime',element:'fire',hp:55,damage:8,speed:140,range:90,art:'A stocky orange-red salamander, glowing charcoal back plates, tiny smoky horns, golden flame tail, cute determined face'},
  'gear-beetle':{name:l('發條甲蟲','Gear Beetle'),brain:'shield',element:'lightning',hp:86,damage:9,speed:90,range:95,art:'A small brass clockwork beetle, indigo wing shell, copper winding key on back, electric cyan antenna tips, stubby segmented legs'},
  'frost-bat':{name:l('霜翼蝠','Frost Bat'),brain:'thrower',element:'ice',hp:39,damage:6,speed:120,range:470,art:'A fluffy pale-blue bat with snowflake shaped wings, small lavender ears, frost crystal necklace and bright expressive face'},
  'storm-kite':{name:l('雷風紙鳶','Storm Kite'),brain:'thrower',element:'wind',hp:45,damage:7,speed:130,range:510,art:'A living bird-shaped indigo kite, gold lightning zigzag markings, flowing fabric tail ribbons, ivory beak and mischievous eyes'},
  'root-pod':{name:l('纏根花苞','Root Pod'),brain:'thrower',element:'nature',hp:60,damage:7,speed:75,range:440,art:'A walking mauve flower bud with curling root feet, thick leaf shield petals, glowing chartreuse pollen seeds and sleepy golden eyes'},
  'sand-scarab':{name:l('砂時甲蟲','Sand Scarab'),brain:'slime',element:'earth',hp:63,damage:9,speed:140,range:95,art:'A terracotta scarab with a tiny hourglass dome on its shell, sandy segmented feet, amber-glass pincers and an emerald eye marking'},
  'blank-puppet':{name:l('失名木偶','Nameless Puppet'),brain:'mushroom',element:'psychic',hp:56,damage:8,speed:115,range:85,art:'A small cream wooden theatre puppet with a blank porcelain oval mask, violet ribbon limbs, a single glowing blue eye and a faded ticket scarf'},
  'echo-wisp':{name:l('黯響浮靈','Echo Wisp'),brain:'thrower',element:'lunar',hp:44,damage:7,speed:125,range:480,art:'A soft smoky violet wisp in the silhouette of a little fox, floating fractured crystal crescent ears, amber eyes, trailing starlight ribbons'},
};
export const ADVENTURE_BOSSES={
  'letter-knight':{name:l('封緘騎士','The Sealed-Letter Knight'),brain:'puppet',pattern:'fan',element:'physical',hp:540,damage:13,speed:115,range:130,art:'A stout cream origami knight, huge ruby wax-seal chest emblem, brass nib lance, folded envelope cape, rounded helmet and warm glowing eyes'},
  'reed-heron':{name:l('雨苔鷺','The Rain-Moss Heron'),brain:'squirrel',pattern:'roots',element:'nature',hp:560,damage:13,speed:135,range:440,art:'An elegant moss-green heron mage, pale jade reed crest, broad lily-pad cape, wooden staff topped with a rain pearl, protective stern expression'},
  'tide-shell':{name:l('沉潮龜','The Sunken-Tide Turtle'),brain:'golem',pattern:'tidal',element:'water',hp:640,damage:14,speed:90,range:160,art:'A massive friendly-looking turquoise sea turtle guardian, coral temple shell, pearl gate markings, broad stone flippers, ancient glowing aqua eyes'},
  'ink-octopus':{name:l('墨卷章魚','The Ink Archivist'),brain:'squirrel',pattern:'fan',element:'psychic',hp:590,damage:13,speed:120,range:500,art:'A deep indigo octopus librarian, parchment scroll tentacles, gold spectacles, ink bottle cap, magical floating tiny books and lavender runes'},
  'beacon-heron':{name:l('風暴守燈者','The Storm Beacon Keeper'),brain:'squirrel',pattern:'storm',element:'wind',hp:630,damage:14,speed:145,range:500,art:'A tall storm-blue heron lighthouse keeper, brass lantern breastplate, yellow rain cape, wind-swept white crest and resolute face'},
  'furnace-lion':{name:l('爐芯獅','The Furnace Lion'),brain:'puppet',pattern:'flame',element:'fire',hp:650,damage:15,speed:120,range:160,art:'A rounded brass automaton lion, molten orange furnace window chest, elaborate blazing mane, heavy charcoal paws, forge insignia and fierce amber eyes'},
  'clock-owl':{name:l('擺鐘貓頭鷹','The Pendulum Owl'),brain:'squirrel',pattern:'orbit',element:'earth',hp:650,damage:14,speed:125,range:470,art:'A wide-eyed bronze clockwork owl, silver pendulum waist, ivory clock-face chest, big layered brass wings, teal glass eye lenses and gear feather crown'},
  'frost-mirror-fox':{name:l('霜鏡狐','The Frost-Mirror Fox'),brain:'puppet',pattern:'ice',element:'ice',hp:670,damage:14,speed:150,range:145,art:'An elegant arctic fox guardian with four flowing translucent ice tails, silver mirror shoulder plates, sapphire forehead crystal and sorrowful blue eyes'},
  'snow-mammoth':{name:l('冬行巨象','The Winter Rail Mammoth'),brain:'golem',pattern:'ice',element:'ice',hp:730,damage:15,speed:85,range:175,art:'A stocky pale-blue woolly mammoth locomotive guardian, brass rail conductor helmet, frosted steam-engine saddle, icy tusks and soft violet eyes'},
  'thunder-ray':{name:l('雷帆魟','The Thunder-Sail Ray'),brain:'squirrel',pattern:'storm',element:'lightning',hp:700,damage:15,speed:150,range:500,art:'A majestic violet manta ray sky pirate, expansive living sail wings with gold lightning veins, tiny brass compass harness, luminous cyan eyes and ribbon tail'},
  'root-stag':{name:l('倒懸鹿','The Hanging-Garden Stag'),brain:'golem',pattern:'roots',element:'nature',hp:710,damage:14,speed:115,range:165,art:'A dignified white stag with golden branching antlers hung with purple blossoms, verdant root armour, pink flower chest seal, dark gentle eyes and curling vine hooves'},
  'hourglass-sphinx':{name:l('沙漏獅','The Hourglass Sphinx'),brain:'puppet',pattern:'orbit',element:'earth',hp:720,damage:15,speed:125,range:160,art:'A compact ochre winged sphinx lion, transparent amber hourglass chest, lapis feather wings, ornate brass mask crown, sandstone paws and inquisitive green eyes'},
  'blank-marionette':{name:l('無名戲偶','The Nameless Marionette'),brain:'squirrel',pattern:'fan',element:'psychic',hp:730,damage:15,speed:130,range:490,art:'A towering but charming ivory wooden theatre marionette, smooth porcelain crescent mask, purple silk cape with faded stars, silver joint rings and prismatic glowing eye'},
  'moon-gate-knight':{name:l('月門衛士','The Moon-Gate Sentinel'),brain:'puppet',pattern:'crescent',element:'lunar',hp:760,damage:16,speed:140,range:170,art:'A silver and midnight-blue armoured rabbit knight, crescent moon shoulder shield, long pale ears, star lantern visor, curved silver glaive and sweeping indigo cape'},
  'echo-hydra':{name:l('三重黯響','The Threefold Echo'),brain:'golem',pattern:'echo',element:'lunar',hp:800,damage:16,speed:100,range:180,art:'A rounded violet crystal dragon with three expressive heads, one orange flame head, one icy cyan head, one jade wind head, cracked starlight belly and sturdy feet'},
  'moon-ferryman':{name:l('月舟','Moonferry'),brain:'squirrel',pattern:'crescent',element:'lunar',hp:830,damage:16,speed:150,range:510,art:'An adult silver fox ferryman in a moon-blue travelling cloak, long ears, kind tired violet eyes, a cracked porcelain moon mask pushed to one side, silver lantern staff and star-thread scarf'},
  'echo-heart':{name:l('黯響之心','The Heart of the Dark Echo'),brain:'golem',pattern:'echo',element:'psychic',hp:900,damage:17,speed:100,range:185,art:'A magnificent floating dark-crystal phoenix spirit, violet and midnight-blue shards, bright cyan star-heart, crown of four coloured elemental orbit rings, wide luminous feather wings, readable mystical face, no horror'},
};

// title, setting, four section names, boss, enemy palette, visual direction
const definitions=[
  ['sunny-training','熄滅的晨光','A Morning Without Light','陽光訓練場','Sunlit Training Grounds',['晨光廣場','木偶防線','星屑長廊','隊長的誓言'],['Dawn Square','Puppet Line','Stardust Walk','The Captain’s Promise'],'puppet',['mushroom','shield'],'A sunlit pet training village, abandoned obstacle course, footprints of stardust, sealed wooden gate'],
  ['windbell-forest','沉默的風鈴','The Silent Bells','風鈴森林','Windbell Woods',['無聲林口','逆風樹道','失落鈴橋','風鈴樹頂'],['Silent Trail','Headwind Path','Lost Bell Bridge','Bell Treetop'],'squirrel',['mushroom','thrower','slime'],'A jade forest of silent bells, wind-bent trees, mossy stone bridge, huge guardian bell tree'],
  ['starcrystal-cave','願望的裂痕','Cracks in a Wish','星晶洞穴','Starcrystal Cavern',['微光洞口','裂晶迴廊','願望迴聲','星心祭壇'],['Glimmer Entrance','Cracked Hall','Chamber of Wishes','Starlight Altar'],'golem',['mushroom','thrower','shield','slime'],'A blue-violet crystal cavern of captured wishes, cracked reflecting crystals and an ancient star altar'],
  ['starlamp-harbor','未寄出的信','The Unsent Letter','星燈港','Starlamp Harbor',['歸航碼頭','封信街道','舊郵局','燈港大門'],['Homebound Dock','Sealed-Letter Street','Old Post Office','Harbor Gate'],'letter-knight',['paper-sentry','echo-wisp','shield'],'A magical seaside postal harbor at twilight, warm star lanterns, paper-letter stalls, a weathered postal tower and sealed sea gate'],
  ['rainleaf-marsh','泥水下的名字','Names Beneath the Rain','雨葉沼澤','Rainleaf Marsh',['雨葉渡口','毒苔小徑','沉字水潭','蘆葦祭台'],['Rainleaf Landing','Moss Trail','Pool of Names','Reed Altar'],'reed-heron',['reed-frog','root-pod','slime'],'A lush rain-soaked wetland, giant lily pads, purple moss, lost glowing letter fragments under water, a broad reed shrine'],
  ['sunken-tide-city','不肯退去的潮','The Tide That Would Not Leave','潮汐古城','Sunken-Tide City',['潮門外街','珊瑚守道','淹沒廣場','貝殼王庭'],['Tide-Gate Street','Coral Guardway','Drowned Square','Shell Court'],'tide-shell',['tide-crab','bubble-jelly','paper-sentry'],'A breathable magical underwater city with azure domes, coral columns, flooded courtyard reflected in pearl glass, huge shell gate'],
  ['coral-archive','空白的那一頁','The Blank Page','珊瑚書庫','Coral Archive',['漂書走廊','墨流書架','封存讀室','無字書壇'],['Drifting-Book Hall','Inkflow Shelves','Sealed Reading Room','Wordless Lectern'],'ink-octopus',['bubble-jelly','paper-sentry','echo-wisp'],'An underwater coral library, floating illuminated books, indigo ink streams, shelves of shell-bound letters, a circular empty-book dais'],
  ['storm-beacon','遲到一年的回覆','An Answer One Year Late','暴雨燈塔','Storm Beacon',['風浪石階','斷纜平台','失訊燈室','暴風燈頂'],['Storm Steps','Broken-Cable Deck','Silent Lamp Room','Beacon Summit'],'beacon-heron',['storm-kite','tide-crab','bubble-jelly'],'A dramatic stormy lighthouse, broad stone sea walkways, broken golden cables, blue-white signal lenses and a windswept beacon platform'],
  ['ember-forge','為誰鑄造的面具','A Mask Forged for Whom','熔火工坊','Ember Forge',['熔銅通道','煤火機廊','面具熔爐','爐芯之門'],['Copper Channel','Coalwork Hall','Mask Furnace','Furnace Gate'],'furnace-lion',['ember-salamander','gear-beetle','shield'],'A grand fantasy forge with molten copper channels, gear machinery, cooling mask moulds, warm orange sparks and a lion-shaped furnace gate'],
  ['ashen-clocktower','被停住的鐘聲','The Bell That Stopped','灰燼鐘樓','Ashen Clocktower',['灰鐘入口','發條長階','停時鐘室','擺鐘平台'],['Ashen Entry','Clockwork Steps','Stopped-Clock Room','Pendulum Deck'],'clock-owl',['gear-beetle','ember-salamander','paper-sentry'],'A bronze astronomical clocktower over ash-grey rooftops, giant exposed gears, stopped ivory clock faces, floating golden pendulum hall'],
  ['frost-mirror-field','鏡子不會說的話','What the Mirror Cannot Say','霜鏡雪原','Frost-Mirror Fields',['碎雪營地','映影冰道','往日鏡廊','霜鏡之心'],['Snow Camp','Reflection Path','Memory-Mirror Hall','Mirror Heart'],'frost-mirror-fox',['frost-bat','blank-puppet','echo-wisp'],'A sparkling snowfield under aurora, enormous ice mirrors reflecting indistinct memories, sapphire crystal arches and silver-blue mirror shrine'],
  ['winter-rail','載著名字的列車','The Train Carrying Names','冬眠列車','Winter Rail',['雪封車站','凍結軌道','無名車廂','冬行車頭'],['Snowbound Station','Frozen Track','Nameless Carriage','Winter Engine'],'snow-mammoth',['frost-bat','gear-beetle','blank-puppet'],'A magical snowbound railway through mountains, broad station platforms, ice-blue track bridges, warm abandoned train carriages and a mammoth-shaped steam engine'],
  ['thunder-ridge','風暴中的選擇','A Choice in the Storm','雷脊群島','Thunder-Ridge Isles',['雷港懸台','電帆索橋','折星風眼','雷帆主桅'],['Thunder Landing','Electric-Sail Bridge','Broken-Star Eye','Thunder Mast'],'thunder-ray',['storm-kite','gear-beetle','echo-wisp'],'Floating storm islands above cobalt clouds, brass lightning rods, sweeping airship sail bridges, an amber star compass and electric sky mast'],
  ['hanging-garden','永遠不變的幸福','Happiness That Never Changes','倒懸花園','Hanging Gardens',['倒樹庭院','纏夢花道','昨日溫室','不散花冠'],['Inverted Court','Dreamroot Walk','Yesterday’s Glasshouse','Unfading Crown'],'root-stag',['root-pod','reed-frog','blank-puppet'],'A surreal suspended garden, upside-down flowering trees, violet roots and glasshouses of nostalgic scenes, golden antler-shaped garden crown'],
  ['hourglass-labyrinth','第二次的答案','An Answer the Second Time','沙漏迷宮','Hourglass Labyrinth',['流砂門廊','重複石道','未來沙室','沙漏心庭'],['Sandflow Gate','Repeating Walk','Tomorrow’s Chamber','Hourglass Heart'],'hourglass-sphinx',['sand-scarab','paper-sentry','echo-wisp'],'An elegant golden desert labyrinth with ancient sandstone walks, hanging hourglasses, lapis inlays, soft dunes and a giant time-glass courtyard'],
  ['nameless-theater','沒有名字的掌聲','Applause Without a Name','無名劇院','Nameless Theater',['褪票大廳','換角後台','失名觀眾席','空白舞台'],['Faded-Ticket Lobby','Changing Backstage','Nameless Seats','Blank Stage'],'blank-marionette',['blank-puppet','echo-wisp','gear-beetle'],'An opulent abandoned midnight theatre, faded tickets, velvet violet curtains, masks without names, empty golden audience seats and an illuminated blank stage'],
  ['moon-gate-fortress','把門留給明天','Leave the Gate for Tomorrow','月門要塞','Moon-Gate Fortress',['月門吊橋','封願城道','碎印內庭','月衛之誓'],['Moon-Gate Bridge','Sealed-Wish Walk','Broken-Seal Court','Sentinel’s Promise'],'moon-gate-knight',['paper-sentry','blank-puppet','echo-wisp'],'A silver crescent fortress above violet clouds, broad moonstone bridges, locked wish emblems, broken star seals and a glowing crescent gate'],
  ['echo-battlefield','害怕也能站在一起','Together Even in Fear','回聲戰場','Echo Battlefield',['勇氣殘道','信任斷橋','共鳴碎庭','三響核心'],['Courage Ruins','Trust Bridge','Harmony Court','Threefold Core'],'echo-hydra',['ember-salamander','frost-bat','storm-kite','root-pod'],'A vast fractured star battlefield, orange courage crystals, cyan trust bridge, jade harmony ruins, three interwoven luminous elemental streams at a central violet core'],
  ['starbridge-duel','我仍記得你','I Still Remember You','星橋決戰','Starbridge Crossing',['裂星橋口','月舟舊站','未寄信台','星橋盡頭'],['Broken-Star Entry','Moonferry’s Stop','Unsent-Letter Deck','End of the Bridge'],'moon-ferryman',['echo-wisp','blank-puppet','storm-kite'],'An epic moonlit star bridge over a cosmic ocean, broken but traversable silver platforms, an old lantern ferry stop, floating unopened letters and a vast full moon'],
  ['dawn-star-court','讓每個願望有回聲','Let Every Wish Find an Answer','黎明星庭','Dawn Star Court',['重光星門','同行長路','萬願之環','黎明星心'],['Relit Star Gate','Companions’ Path','Ring of Wishes','Dawn Starheart'],'echo-heart',['ember-salamander','frost-bat','gear-beetle','root-pod'],'A breathtaking celestial dawn courtyard, shattered dark crystal giving way to warm golden starlight, four elemental wish streams, a huge luminous starheart altar and a sunrise paradise horizon'],
];
export const ADVENTURE_CHAPTER_DESIGNS=definitions.map((d,n)=>({id:d[0],number:n+1,act:Math.floor(n/4),title:l(d[1],d[2]),name:l(d[3],d[4]),sections:d[5].map((name,i)=>l(name,d[6][i])),boss:d[7],enemies:d[8],art:d[9],colors:n<4?[0xb8d9c2,0xeed7a4]:n<8?[0x82bbcd,0xc6e4dc]:n<12?[0x858ab9,0xc9d9e8]:n<16?[0xc09bc9,0xe7d2a1]:[0x7373ae,0xdbc8f0]}));
