export const STORY_ACT3=[
 {number:9,summary:['燭鱗曾替月舟鑄造面具，如今必須面對善意造成的後果。','Emberscale forged Moonferry’s mask. Now he must face the consequences of his good intentions.'],scenes:[
  [['narrator','熔火工坊的每座爐子都在燒，卻沒有工匠敢靠近。地上的面具模具，全都沒有嘴。','Every furnace burns, yet no smith approaches. None of the mask molds on the floor has a mouth.'],['dragon','我叫燭鱗。月舟說要一副能隔開恐懼的面具，我就替他造了。我以為是在幫忙。','I am Emberscale. Moonferry asked for a mask to keep fear away. I forged it, thinking I was helping.'],['hero','你願意讓我們看看圖紙嗎？我們需要知道，它究竟隔開了哪些東西。','Will you show us the drawings? We need to know what the mask truly keeps away.']],
  [['dragon','煤火蠑螈會讓人燃燒，別停在同一條路上。爐芯的火有預兆，看見亮起就先離開。','Ember salamanders can set you burning. Watch the furnace warning and move before the fire reaches you.'],['paperfox','圖紙把「擔心朋友」也列成恐懼。只要面具一直戴著，朋友的名字就會越來越模糊。','The design counts worrying about friends as fear. The longer the mask is worn, the less clearly their names remain.'],['guide','他想替我們減輕痛苦，卻連自己為甚麼這樣做，都會慢慢忘掉。','He wanted to ease our pain, yet will slowly forget why he wanted to do it.']],
  [['narrator','面具熔爐裏留著另一張圖紙，角落寫著「靜願機：以一人承載換成所有人無牽掛」。','A second drawing lies in the furnace: “Quiet-Wish Engine: replace one person’s burden with bonds removed from everyone.”'],['dragon','我當時只看見「不用再有一個人受苦」。後面那半句，我沒有追問。','I saw only “No one must carry the pain alone.” I never questioned the rest.'],['hero','那就從現在開始追問。你做得出封住願望的機器，也可以幫忙找打開它的方法。','Then start questioning now. If you helped build the lock, you can help us find how to open it.']],
  [['furnace-lion','冷卻停止！所有面具必須完成，所有聲音必須安靜！','Cooling halted! Every mask must be finished. Every voice must be quiet!'],['dragon','爐芯獅，你以前會等工匠喊「完成」才關爐。誰把這道命令改了？','Furnace Lion, you used to wait for the smith’s approval. Who changed your orders?'],['furnace-lion','工匠會猶豫。機器不應猶豫！','Smiths hesitate. A machine must never hesitate!'],['hero','猶豫讓人有機會察覺錯誤。我們會把停爐的選擇交還給燭鱗。','Hesitation gives us a chance to notice a mistake. We will return the shutdown choice to Emberscale.'],['dragon','這一次，我會站在自己的作品前面。別讓火把圖紙燒掉，我要親手改好它。','This time I will stand before my own creation. Save the drawings. I will put them right myself.']],
 ],ending:[['dragon','找到冷卻芯了。靜願機一旦全開，只有星橋上的原始鈴印能讓它停下。','We found the cooling core. Once the engine fully opens, only the original bell seal on Starbridge can stop it.'],['guide','我的藍鈴只是副印。原始鈴印，應該一直在月舟手上。','My blue bell is only a copy. Moonferry should still have the original.'],['paperfox','應該？雲耳，我們已經不是在查一件普通失物了。請別再用猜測代替你記得的事。','Should? Cloud-Ear, this is no ordinary missing object. Please stop replacing what you remember with guesses.'],['dragon','灰燼鐘樓記錄過星橋啟動的時間。我也同行，這不是把修理交給別人的時候。','Ashen Clocktower recorded the bridge activation. I am coming too. I cannot leave the repair to someone else.'],['narrator','第一座爐子熄下來，大家終於聽見彼此的聲音。雲耳想說的話，卻仍堵在喉嚨裏。','The first furnace cools. At last everyone can hear one another. Cloud-Ear’s words still catch in his throat.']]},
 {number:10,summary:['鐘樓停在事故發生的一刻，隊長送來的舊徽章揭開了守護者的制度。','The clock stopped at the accident. A badge sent by the captain reveals how the guardians’ duty began.'],scenes:[
  [['narrator','灰色屋頂上的鐘，全停在同一分鐘。木偶隊長送來一枚舊徽章，上面刻著「星燈郵差」。','Every rooftop clock has stopped at the same minute. Captain Timber sends a badge marked “Starlamp Courier.”'],['puppet','我想起你戴過它，雲耳。你不只替樂園帶路，也曾替所有守護者送信。','I remember you wearing it, Cloud-Ear. You once carried messages for every guardian.'],['guide','原來我的工作，一直是把大家的聲音送給別人……現在卻連自己的聲音都送不出去。','My work was to carry voices to others… Now I cannot even get my own voice out.']],
  [['dragon','發條甲蟲放電前會亮起觸角。別被逼到兩道電流中間，先留出走位的位置。','Gear beetles light their antennae before discharging. Leave room to move out of their electrical lanes.'],['paperfox','鐘室裏有一份舊約：星晶的光來自願望，留下的恐懼則由一位守印者收起。','An old covenant says the crystal shines with wishes, while a single keeper collects the fear they leave behind.'],['hero','一直由一個人收起？如果連守印者也害怕，又有誰會聽見他？','Only one person? If the keeper is afraid too, who hears them?']],
  [['narrator','停時鐘室重播事故前的一分鐘。月舟請求分擔恐懼，守則卻回答：「守印者不得離崗。」','The clock replays the minute before the accident. Moonferry asks to share his burden. The covenant orders him to stay.'],['dragon','所以他才造靜願機。他想打破守則，卻也開始替所有人決定該留下甚麼。','That is why he built the engine. He wanted to break the covenant, but began deciding everyone else’s lives too.'],['guide','他曾經問過我，願不願意一起改變。我答應了。','He once asked if I would help change things. I said yes.']],
  [['clock-owl','時刻已封存。錯誤的分鐘不准再向前，否則下一次還會有人失敗。','This minute is sealed. A failed moment must never advance, or someone will fail again.'],['puppet','我們曾經也把出口封住，以為這樣便能不再犯錯。這只會讓人停在原地。','I sealed the exits too, believing it would prevent mistakes. It only kept everyone trapped.'],['clock-owl','繼續向前，誰能保證明天安全？','Who can guarantee tomorrow will be safe?'],['hero','沒有人能保證。我們能做的，是把發生過的事記住，一起改變下一次。','No one can guarantee it. We can remember what happened and change what we do next, together.'],['guide','讓鐘再走一次。這次我不會把答應過的事，藏在停住的那一刻。','Let the clock move again. This time I will not hide my promise in a moment that never ends.']],
 ],ending:[['clock-owl','鐘聲恢復了。星橋的那次超載，不是郵差忘記投遞，是恐懼箱早已裝滿。','The bells resume. The bridge failed because the chest of fear was already full, not because a delivery was forgotten.'],['guide','月舟早就知道會超載。我們去找新的地方分擔，卻在雪原被攔住了。','Moonferry knew it was overloaded. We sought somewhere to share the burden, but were stopped on the snowfield.'],['paperfox','你終於說「我們」了。謝謝你，但還有沒說出的部分，對嗎？','You finally said “we.” Thank you. But there is more you have not told us, isn’t there?'],['hero','下一站去霜鏡雪原。雲耳可以慢慢說，我們也可以清楚問，誰都不必獨自猜。','Next, Frost-Mirror Fields. Cloud-Ear can speak slowly, and we can ask clearly. None of us must guess alone.'],['narrator','隊長把舊徽章放進雲耳手裏。鐘樓開始走向下一分鐘，過去卻仍在等待一個完整的回答。','The captain places the badge in Cloud-Ear’s hand. The clock moves forward. The past still waits for a complete answer.']]},
 {number:11,summary:['冰鏡映出真實的過去，也映出人最想相信的版本。','Ice mirrors reveal the past—and the version of it we most want to believe.'],scenes:[
  [['narrator','雪地上立著一排鏡子。每個人都看見自己想重來的一刻，卻沒有兩面鏡子完全一樣。','Mirrors stand across the snow. Each shows a moment someone wishes to relive, yet no two reflections are the same.'],['paperfox','我的鏡子裏，父親終於收到了回信。可是那張郵戳，根本不是那一年的。','In my mirror, my father receives his letter at last. But its stamp belongs to the wrong year.'],['hero','鏡子會放大我們的願望。別只憑一幅好看的畫面，就決定它是真相。','A mirror may magnify what we wish. A beautiful reflection alone does not make it true.']],
  [['dragon','霜翼蝠的冰彈能讓人短暫結冰。看到冰圈先走開，防禦擋住後再找空檔接近。','Frost shots can briefly freeze you. Move out of the ice circles, then approach through the opening.'],['guide','鏡子裏的我，把箱子交給了月舟，說「不用再讓你一個人背」。這句話，我真的說過。','My reflection gives Moonferry the chest: “You must not carry it alone.” I truly said those words.'],['paperfox','那就把它當成一塊碎片。我們還需要知道，你們後來怎麼做。','Then keep it as one piece. We still need to know what you did next.']],
  [['narrator','舊日鏡廊映出雪原的拒絕：沒有人願意接過恐懼箱。月舟站在雪裏，第一次戴上了面具。','The hall shows the snowfield’s refusal. No one will take the chest. Standing in the snow, Moonferry first puts on the mask.'],['guide','我以為只要找到足夠多人，一定能分擔。可是我們被一扇又一扇門拒絕。','I thought enough people could share it. But door after door turned us away.'],['hero','拒絕過你們的人，也有不知道和害怕的時候。這不能抹掉傷害，卻能告訴我們要改變甚麼。','People may refuse through fear or ignorance. That does not erase the hurt, but shows us what must change.']],
  [['frost-mirror-fox','留在鏡子裏。這裏可以重寫每一次拒絕，讓你永遠不會被辜負。','Stay in the mirror. Every refusal can be rewritten here. No one will disappoint you again.'],['paperfox','如果我只跟鏡中的父親說話，真正沒收到的那封信，又有誰會去找？','If I speak only to my father’s reflection, who will seek the letter he never received?'],['frost-mirror-fox','真實會傷人。鏡子至少不會離開你。','Reality hurts. At least a mirror will never leave you.'],['guide','但它也不會在我做錯時提醒我。我需要能回答的人，不只是一個總說好的影子。','It cannot tell me when I am wrong. I need someone who answers, not a shadow that always agrees.'],['hero','讓冰鏡退下。那段被拒絕的過去，我們會一起帶回真正的世界。','Lower the mirrors. We will carry that painful past back into the real world together.']],
 ],ending:[['frost-mirror-fox','最後一面真鏡，我一直不敢讓人看。上面是星橋出發前，雲耳親手封住自己的名字。','I hid the last true mirror. It shows Cloud-Ear sealing his own name before crossing Starbridge.'],['paperfox','親手封住？這不是單純被人拿走的記憶。雲耳，你做過甚麼？','By your own hand? Your memories were not simply stolen. Cloud-Ear, what did you do?'],['guide','我……怕自己在橋上退縮。所以請月舟先把我的恐懼拿走，讓我能把箱子送完。','I… feared turning back on the bridge. I asked Moonferry to remove my fear so I could finish the delivery.'],['hero','先離開雪原，找一個安全的地方把經過說清楚。大家有權知道，你也有權把話說完。','Let’s leave the snowfield and talk somewhere safe. Everyone deserves the truth, and you deserve time to tell it.'],['narrator','雪裏傳來列車汽笛。紙尾走在雲耳前面，這一次，沒有把航圖攤在兩人中間。','A train whistle sounds across the snow. Papertail walks ahead. This time, he does not place the map between them.']]},
 {number:12,summary:['列車載著被遺忘的人，嚮導終於說出自己的選擇；信任需要時間重新建立。','A train carries the forgotten. The guide admits his choice, and trust must be rebuilt in time.'],scenes:[
  [['narrator','冬眠列車每晚靠站，乘客卻說不出自己的名字。售票員仍替他們保留回家的座位。','Winter Rail stops each night, carrying passengers who cannot name themselves. Their seats home are kept waiting.'],['guide','我曾經以為，拿走害怕便能勇敢。可沒有害怕的我，也沒察覺箱子在超載。','I thought removing fear would make me brave. Without it, I failed to notice the chest overloading.'],['hero','你現在察覺了。先幫車上的人脫離封印，再把這次發現變成你要做的事。','You notice it now. Let’s help these passengers, then turn that understanding into action.']],
  [['dragon','車廂的暖爐被冰封了。清出軌道，讓熱氣重新送進去，別讓霜翼蝠把路封死。','The carriage heaters are frozen. Clear the track and restore the warmth before the frost bats seal it.'],['paperfox','我會救人，不表示我已經相信你。你隱瞞的事，讓我們一直靠猜測前進。','I will help them. That does not mean I trust you yet. Your silence kept us moving by guesses.'],['guide','我明白。我不會再用「怕你們失望」作理由。你問甚麼，我就把知道的部分說清楚。','I understand. I will not hide behind fear of disappointing you. Ask, and I will tell what I know.']],
  [['guide','星橋崩裂時，月舟救了我。面具連我的名字也封住了，我忘記他，平安回了樂園。','When the bridge broke, Moonferry saved me. The mask sealed my name too. I forgot him and returned safely.'],['paperfox','而他留在另一邊，看著所有人把事故記成「投遞完成」……','He remained on the far side, while everyone recorded the accident as “Delivery completed”…'],['guide','醒來後的我很快樂，卻不知道快樂是怎樣換回來的。這次，我不想再把代價留給他一個人。','I woke happy, not knowing what that safety had cost him. This time I will not leave the cost to him alone.']],
  [['snow-mammoth','車不能向前。乘客的目的地不存在，開車就是把他們送進下一場失去。','The train cannot move. Their destinations no longer exist. Moving means another loss.'],['paperfox','他們忘記了目的地，不表示那裏沒有等他們的人。','Forgetting a destination does not mean nobody is waiting there.'],['snow-mammoth','我只收到停車的命令。沒有新的命令，我怎樣敢帶大家走？','My orders say to stop. Without new orders, how can I dare take them forward?'],['guide','我曾是郵差。今天的新命令，我會親自送到每一位守護者手上：名字要送回原本的人。','I was a courier. Today I will deliver a new message: return every name to its owner.'],['hero','冬行巨象，請跟我們一起把這條路重新打開。','Winter Mammoth, help us reopen this route together.']],
 ],ending:[['snow-mammoth','汽笛響了。第一位乘客想起自己的家，車票上重新亮起一個字。','The whistle sounds. One passenger remembers home, and a word returns to their ticket.'],['guide','紙尾，我對不起你。我知道道歉不會把信任變回來，但我會把承諾做給你看。','Papertail, I am sorry. An apology cannot restore trust by itself. I will show you by keeping my promises.'],['paperfox','我需要時間。但我會繼續同行，也會繼續問清楚。請別把我的問題當成拒絕。','I need time. I will keep traveling and keep asking. Please do not mistake my questions for rejection.'],['dragon','月舟的機器正送往雷脊群島。我已改好冷卻芯，我們還有阻止它的機會。','The engine is heading to Thunder-Ridge Isles. I repaired the cooling core. We can still stop it.'],['narrator','列車駛過雪原。雲耳沒有坐到最安靜的角落，而是把藍色日記放在大家都能看見的桌上。','The train crosses the snow. Cloud-Ear sets his diary on the shared table instead of hiding in a quiet corner.']]},
];
