// Long-form original dialogue. Each chapter supplies four encounter scenes and
// a resolution; its physical setting and combat cast come from adventure-design.
export const STORY_ACT2=[
 {number:4,summary:['樂園重新亮起，一封寫著嚮導名字的舊信，卻讓旅程走向另一片海。','The paradise lights return, but an old letter addressed to the guide leads toward another sea.'],scenes:[
  [['narrator','歸航的船上掛滿星燈。大家都在慶祝，雲耳卻反覆撫摸頸上的藍鈴，像在等一個沒有赴約的人。','Star lamps adorn the homebound boats. While everyone celebrates, Cloud-Ear keeps touching his blue bell.'],['guide','我也應該高興的。可是鈴一響，就會想起一座橋……和一隻沒有握住的手。','I should be happy. But the bell reminds me of a bridge… and a hand I failed to hold.'],['paperfox','別急著替記憶編答案。我叫紙尾，負責畫航圖。先看看這封積壓了一年的信。','I am Papertail, the harbor cartographer. Before guessing at memories, look at this letter, undelivered for a year.'],['hero','收件人是雲耳。寄件人的名字，為甚麼被塗掉了？','It is addressed to Cloud-Ear. Why has the sender’s name been crossed out?']],
  [['paperfox','封信街的紙甲衛兵只准已登記的名字通過。近來，登記冊每天都少幾頁。','The paper sentries admit only registered names. Pages have been disappearing from their register.'],['guide','這裏的路我明明沒走過，卻知道第三個路口要轉彎。我到底忘了多少？','I have never been here, yet I know the third turning. How much have I forgotten?'],['hero','先讓衛兵恢復正常，再找原本的登記。知道得少，也可以一步一步查清楚。','Free the sentries first, then find the original register. We can uncover the truth one step at a time.']],
  [['narrator','舊郵局裏，信封像受驚的鳥四處飛散。紙尾在一枚舊郵戳上，找到與藍鈴相同的星橋圖案。','Envelopes flutter through the old post office. Papertail finds a stamp bearing the same bridge as the blue bell.'],['paperfox','一年前，星橋發生過事故。從那天起，所有寄給「月舟」的信，都退回了。','An accident struck Starbridge a year ago. Since then, every letter to “Moonferry” has been returned.'],['guide','月舟……這個名字讓我很難過。可是我連他是誰，都說不出來。','Moonferry… That name hurts. Yet I cannot even say who he is.']],
  [['letter-knight','停止投遞！寄件人不存在，這封信便不應該存在！','Stop the delivery! If the sender does not exist, neither should this letter!'],['paperfox','一本名冊不能決定誰曾經活過。信沒有收到，約定也不會自動消失。','A register cannot decide who once lived. An unanswered letter does not erase a promise.'],['letter-knight','守則只教我把錯誤封住。若我放行，又害了一個人怎麼辦？','My orders tell me to seal mistakes away. What if letting it through hurts someone?'],['hero','那就跟我們一起確認。你可以守護這封信，不必永遠扣住它。','Then help us check the truth. You can protect the letter without holding it forever.'],['guide','我想知道答案。即使那是我做錯的事，也請讓我親自讀完。','I want the answer. Even if I made a mistake, please let me read it myself.']],
 ],ending:[['letter-knight','封印解開了……原來我守著的，不是錯信，是一個一直等不到的回覆。','The seal is broken… I was guarding an answer that never arrived.'],['guide','信上只剩一句：「答應我，別讓名字再次消失。」下面的墨水，被海潮洗掉了。','Only one sentence remains: “Promise me—do not let names disappear again.” The tide has washed away the rest.'],['paperfox','原件曾經泡在雨葉沼澤。我會跟你們同行，但雲耳，別把看見的東西藏起來。','The original was soaked in Rainleaf Marsh. I will come with you, Cloud-Ear. Please do not hide what you find.'],['hero','從今天開始，我們不只尋找星光，也尋找星光曾經照著的人。','From today, we seek not only starlight, but the people it once shone upon.'],['narrator','紙尾畫下新航線。藍鈴響了一聲，很輕，卻像遠方有人終於聽見了。','Papertail draws a new route. The blue bell rings softly, as if someone far away has finally heard.']]},
 {number:5,summary:['泥水藏著被沖走的名字，守護沼澤的雨苔鷺拒絕再相信外來者。','The marsh holds washed-away names, and its guardian refuses to trust another outsider.'],scenes:[
  [['narrator','沼澤的雨沒有停過。木牌上的名字被泡成空白，渡口仍放著等人來接的行李。','Rain never stops in the marsh. Names have washed off the signs, and luggage waits for owners who never return.'],['paperfox','這些不是垃圾，是有人回家的證明。小心雨葉蛙，它們的種子會讓腳步變慢。','These are traces of someone’s way home. Reed frogs fire seeds that can slow your steps.'],['hero','先把渡口清出來。等我們找回名字，還要有人能從這裏回家。','Clear the landing first. When we recover their names, they will need a way home.']],
  [['guide','這塊布上的縫線，跟我的郵袋一樣。可是我記得自己從來沒有郵袋。','The stitching on this cloth matches my mailbag… but I do not remember owning a mailbag.'],['paperfox','你剛才說「我的」。記憶沒有全不見，身體還記得你做過的事。','You just said “my.” Your memory is not entirely gone. Your body remembers what you did.'],['hero','不用逼自己一次想起全部。先把每一件找到的東西保存好。','You do not have to remember everything at once. Let’s keep every piece we find safe.']],
  [['narrator','水潭底的字緩緩浮起：「第七次投遞，雲耳、月舟。」另一行寫著：「星晶承載已達上限。」','Words rise from the pool: “Seventh delivery: Cloud-Ear and Moonferry.” Another line reads: “Crystal capacity exceeded.”'],['guide','我不是第一次見他。我們曾經……一起送過很多人的願望。','We did not meet only once. We… carried many people’s wishes together.'],['paperfox','星晶會滿？樂園從沒告訴過大家這件事。雨苔鷺一定知道更多。','The crystal can fill up? Nobody in the paradise told us. The heron must know more.']],
  [['reed-heron','你們又來取走名字？上一次，拿走的人說是為了保護，卻再也沒有送回來！','Have you come to take more names? Last time, someone promised protection, then never returned them!'],['guide','上一次……是我來過嗎？如果是，請把我做的事告訴我。','Was I here last time? If I was, please tell me what I did.'],['reed-heron','你連承諾都忘了，叫我怎樣相信你？','You forgot your promise. How can I trust you?'],['hero','我不能替他證明過去。但今天，渡口已經重新打開，我們會把找到的東西留下。','I cannot prove his past. But today we reopened the landing, and we will leave what we find with you.'],['paperfox','請先讓黯霧離開你的翅膀。等你能清楚說話，我們才有機會把這件事做好。','First, let us free your wings from the mist. Then we can hear you clearly and put things right.']],
 ],ending:[['reed-heron','雲耳曾帶走願望，不是名字。名字消失，是那座新機器啟動以後的事。','Cloud-Ear carried wishes, not names. The names vanished after a new machine was started.'],['guide','謝謝你仍願意告訴我。我不會要求你立刻原諒，只會把今天答應的事做好。','Thank you for telling me. I will not ask for instant forgiveness. I will keep today’s promise.'],['paperfox','泥下還有一本潮汐古城的航誌。機器的零件，是沿著水路運走的。','A Sunken-Tide log lies beneath the mud. The machine’s parts were shipped along the waterway.'],['hero','把航誌帶上，名字留在渡口。我們查清楚以後，會回來讀給大家聽。','Take the log, leave the names here. When we learn the truth, we will return to read it to everyone.'],['narrator','雨苔鷺把失去名字的木牌重新立起，暫時只寫上：「有人正在回家的路上。」','The heron raises the blank signs again. For now, they say: “Someone is on the way home.”']]},
 {number:6,summary:['海潮封住古城，沉潮龜用堅硬的貝殼守著一個無法履行的承諾。','The tide seals an ancient city, where a turtle guards a promise he cannot fulfill.'],scenes:[
  [['narrator','水晶罩隔開海水，古城的街道仍能行走。鐘聲卻困在水裏，每家門前都有未拆的信。','Crystal domes hold back the sea. The streets remain passable, but bells and unopened letters wait in silence.'],['tideguide','我是渡潮，替這裏照顧潮汐。城門已經關了一年，說是等所有人都安全，才准離開。','I am Tideway, the tide keeper. The gate has been shut for a year, until everyone is declared safe.'],['hero','如果安全的條件永遠達不到，這裏就變成另一座牢籠了。','If that condition can never be met, the city becomes a prison.']],
  [['tideguide','潮甲蟹習慣正面守住，從側邊繞過去。泡泡水母會留下水氣，要小心後面的電流。','Crabs defend from the front. Circle around them. Jelly bubbles leave water that can carry an electric shock.'],['paperfox','這裏的敵人都帶著郵局的封條。誰把「不要離開」寫成了整座城的命令？','These guards wear postal seals. Who turned “do not leave” into an order for a whole city?'],['guide','那封條是月舟的習慣……他以前總會替淋濕的信，再包一層紙。','Moonferry used those seals… He always wrapped rain-soaked letters in another layer of paper.']],
  [['narrator','淹沒的廣場上，一顆記憶珍珠映出兩名郵差。月舟把自己的披風披在年幼的雲耳身上。','A memory pearl shows two couriers. Moonferry wraps his cloak around a younger Cloud-Ear.'],['guide','他不是陌生人。他照顧過我，教我認路……我怎麼能連這些都忘記？','He was not a stranger. He cared for me and taught me the routes… How could I forget him?'],['tideguide','記憶被拿走，不代表感情是假的。先把珍珠收好，這是你們確實相遇過的證明。','Losing a memory does not make the bond false. Keep the pearl. It proves that you knew each other.']],
  [['tide-shell','門不能開！我答應過月舟，絕不讓任何人再被風暴帶走。','The gate must stay closed! I promised Moonferry that no one would be taken by a storm again.'],['hero','我們也想守護大家。但這座城需要選擇，不是永遠等待你的許可。','We want to protect them too. But the city needs a choice, not endless permission to wait.'],['tide-shell','我一放手，就會失去他們。你們沒有看過星橋崩裂時，那些墜落的燈！','If I let go, I will lose them. You never saw the lamps falling when Starbridge broke!'],['guide','我也在那座橋上。如果你一直害怕，請先讓我聽見完整的經過。','I was on that bridge too. If you are afraid, please let me hear what truly happened.'],['tideguide','沉潮，我會和你一起看潮。城門開了，也不表示你再也不用守護。','Deep-Tide, I will watch the sea with you. Opening the gate does not mean abandoning your duty.']],
 ],ending:[['tide-shell','星橋崩裂那晚，月舟救了雲耳。他自己卻留在橋另一端，抱著裝滿願望的箱子。','That night, Moonferry saved Cloud-Ear. He stayed on the far side with a chest full of wishes.'],['guide','不是我沒握住他……是他先把我推回了安全的地方。','It was not simply a hand I failed to hold… He pushed me back to safety.'],['paperfox','郵局的紀錄只寫「投遞完成」。有人把救人的經過，整段刪掉了。','The postal record says only “Delivery completed.” Someone erased the rescue entirely.'],['tideguide','珊瑚書庫保管原始記錄。我陪大家去，那裏的墨流連舊日的聲音也能留下。','Coral Archive keeps the original records. I will come. Its ink can preserve the voices of the past.'],['narrator','潮門緩緩打開。第一次有人離開時，沉潮龜沒有閉上眼睛，而是向他們說了再見。','The tide gate opens. As the first travelers leave, the turtle watches and says goodbye.']]},
 {number:7,summary:['書庫保留過去，卻用空白掩蓋了最重要的一頁；月舟的目的第一次露出輪廓。','The archive preserves history but hides its most important page. Moonferry’s purpose begins to emerge.'],scenes:[
  [['narrator','書頁在水裏自行翻動，每一冊都記著某人的願望。一本薄薄的藍色日記，一直跟著雲耳漂浮。','Books turn their own pages underwater. A thin blue diary keeps drifting after Cloud-Ear.'],['guide','日記認得我，書上的字卻不肯亮起。像是有人不許我讀自己的過去。','The diary knows me, but its words will not light. Someone is keeping me from my own past.'],['paperfox','先找借閱印記。書不會自己封住，總有人留下了開鎖的方法。','Find its lending seal first. Someone locked it, so someone left a way to open it.']],
  [['tideguide','墨流會遮住視線，跟著書架上的金邊走。遇到紙甲衛兵，別一直撞它的盾。','Ink may obscure the path. Follow the gold shelf edges, and do not charge straight into paper shields.'],['paperfox','這本新書叫《零痛苦試驗》，作者的印章跟月舟的封條一樣。','This new book is called “The Zero-Pain Trial.” Its author’s stamp matches Moonferry’s seal.'],['hero','拿走痛苦，聽起來很好。可是書裏怎麼連快樂的回憶，也列成要移除的東西？','Removing pain sounds kind. Why does the book also list happy memories for removal?']],
  [['guide','藍色日記亮了……「雲耳第一次獨自投遞，月舟在終點等他。」我那時一定很開心。','The diary lights up… “Cloud-Ear’s first solo delivery. Moonferry waits at the finish.” I must have been happy.'],['paperfox','下一頁卻是空白。不是因為沒寫，是紙纖維裏所有的墨，都被抽走了。','The next page is blank. It was written, but every trace of ink has been drawn from the fibers.'],['hero','空白不會替任何人減輕責任。我們需要知道，那晚的願望為甚麼失控。','A blank page cannot remove responsibility. We need to know why the wishes went out of control.']],
  [['ink-octopus','過去會讓人痛。我照命令刪掉一頁，就是替你們省下一次傷心。','The past can hurt. Erasing a page saves you another sorrow.'],['guide','那一頁也許有讓我害怕的事，但也有把我救回來的人。','That page may frighten me. It also holds the person who saved me.'],['ink-octopus','你們只在乎記得。若記得會讓人彼此怨恨呢？','You care only about remembering. What if remembering makes people hate each other?'],['paperfox','怨恨要靠事情的經過來解開。把經過拿走，大家只能一直猜。','We need the truth to untangle resentment. Without it, all we can do is guess.'],['hero','請把那一頁交還。答案應該由讀過的人，自己選擇怎樣面對。','Return the page. Those who read it must choose how to face the answer.']],
 ],ending:[['ink-octopus','月舟帶走了一台「靜願機」。它原本只抽走過量的恐懼，後來卻開始抽走名字。','Moonferry took a Quiet-Wish Engine. It first removed excess fear, then began removing names.'],['guide','日記最後一句是他寫的：「只要還有牽掛，痛苦就會回來。」','His final diary line says: “As long as bonds remain, pain will return.”'],['tideguide','他想保護大家，卻開始把彼此的牽掛也當成危險。','He wanted to protect everyone, but began treating their bonds as a danger.'],['paperfox','還有一張去暴雨燈塔的回執。月舟在那裏留下過一封回信，我們不能再讓它被刪掉。','A receipt points to Storm Beacon. Moonferry left a reply there. We cannot let that be erased too.'],['narrator','藍色日記被小心收進郵袋。雲耳第一次沒有躲開那一頁空白，而是在旁邊寫下了今天。','Cloud-Ear puts the diary in his mailbag. Beside its blank page, he writes down today.']]},
 {number:8,summary:['暴風阻隔了回信，也阻隔了嚮導的坦白。舊友的聲音終於穿過燈塔。','A storm blocks the reply and the guide’s confession. An old friend’s voice finally reaches the beacon.'],scenes:[
  [['narrator','燈塔照著所有返航的船，自己的訊號卻已經中斷一年。未送出的回信堆滿石階。','The lighthouse guides returning ships, yet its own signal has been broken for a year. Unsent replies cover the steps.'],['paperfox','我的父親在這裏等過一封信，直到離開也沒有等到。這次，我不會讓回覆再遲到。','My father waited here for a letter that never came. This time, I will not let an answer arrive too late.'],['guide','紙尾……我有些記憶已經回來了。但我還不知道，應該從哪裏說起。','Papertail… Some memories have returned. I do not know where to begin.']],
  [['tideguide','先修斷掉的燈纜。暴風守燈者把風全引來這裏，怕訊號一出去就會惹來追兵。','Repair the lamp cable. The keeper draws the storm here, afraid that a signal will bring pursuers.'],['hero','那些紙鳶是傳訊用的。黯霧把它們變成了風彈，像是害怕任何人聽見真相。','Those kites once carried messages. The mist turns them into attacks, as if it fears the truth being heard.'],['paperfox','如果雲耳已經記起一些事，為甚麼還要由我們一路猜？','If Cloud-Ear remembers something, why are we still being made to guess?']],
  [['guide','我記得星橋的箱子太重，也記得月舟說「先把你送回去」。但每次往後想，頭就很痛。','I remember a chest too heavy for the bridge. Moonferry said, “Let me get you home first.” Remembering more hurts.'],['paperfox','我不是要你一次說完。我只是希望，当你害怕時，也把我們當成能商量的人。','I do not need every answer at once. I need you to trust us when you are afraid.'],['hero','把訊號送出去。等風停下，我們會給這次談話留足夠的時間。','Send the signal. When the wind settles, we will give this conversation the time it needs.']],
  [['beacon-heron','燈不能再亮！月舟說過，回覆會讓人重新牽掛，牽掛就會受傷！','The lamp must stay dark! Moonferry said replies renew our bonds, and bonds bring hurt!'],['paperfox','沒有回覆也會受傷。只是那種傷，守著燈的人看不見。','Silence hurts too. The keeper of the lamp simply cannot see that hurt.'],['beacon-heron','我守了一年，不能在最後放壞人進來！','I have guarded it for a year. I cannot let the wrong people in now!'],['guide','月舟的聲音在燈裏。如果你真想守護他，讓他自己說完。','Moonferry’s voice is in the lamp. If you want to protect him, let him finish speaking.'],['hero','我們會擋住這場風暴，也會讓那封回信抵達。','We will hold back the storm and let that reply reach its destination.']],
 ],ending:[['moon','雲耳，如果你收到這段聲音，別來找我。星晶需要有人保管所有人的恐懼，我正在找另一種方法。','Cloud-Ear, if you hear this, do not look for me. The crystal makes someone carry everyone’s fear. I am seeking another way.'],['guide','他不是想消失。他是怕我知道，他一直在替大家承受甚麼。','He did not want to vanish. He was afraid I would discover what he had been carrying for everyone.'],['paperfox','但那台機器已經開始拿走名字。想法再好，也不能把後果藏起來。','But the engine is already taking names. Good intentions cannot hide the consequences.'],['tideguide','回信裏有熔火工坊的圖樣。面具和機器，都是在那裏造出來的。','The reply contains a forge diagram. Both the mask and the engine were made there.'],['narrator','第一道訊號穿過雲層。紙尾仍沒有說原諒，但她把航圖放在雲耳旁邊，沒有收回自己的座位。','The first signal pierces the clouds. Papertail has not forgiven him, but leaves the map—and a place beside him.']]},
];
