export const STORY_ACT4=[
 {number:13,summary:['雷帆魟把機器當成交換條件；夥伴首次在風暴中公開對抗靜願計畫。','A sky trader uses the engine as a bargaining chip. The companions openly challenge the Quiet-Wish plan.'],scenes:[
  [['narrator','雷脊群島在雲海上漂移。靜願機被拆成四座發亮的錨，正把不同地區的願望拉向同一個方向。','Four glowing engine anchors drift among the Thunder-Ridge Isles, drawing wishes from every region toward one point.'],['dragon','不能只砸開外殼。四道錨一起扯動，星橋會再次超載。我們要先拿到斷開它們的順序。','Breaking the shell could overload Starbridge again. We must learn the order for releasing the anchors.'],['paperfox','我把航圖給大家各留了一份。雲耳，這次由你告訴我們，你看見的路通到哪裏。','Everyone has a copy of the map now. Cloud-Ear, tell us where the route you recognize leads.']],
  [['guide','主桅上的雷印是運送標記。四道錨的目的地，是月門要塞，不是修好的樂園。','The thunder seal is a shipping mark. The anchors are heading to Moon-Gate Fortress, not the restored paradise.'],['tideguide','腳下帶水時更要小心電流。讓雷風紙鳶的光線先過去，再接近發條甲蟲。','Water can carry a stronger shock. Let the lightning pass, then approach the gear beetles.'],['hero','我們不藏起這條航線。把消息送給隊長和松鼠，請他們保護還未被抽走的名字。','Send this route to the captain and squirrel. Ask them to protect the names that remain.']],
  [['narrator','折星風眼中，雷帆魟正和月舟交易。他想換取沒有風暴的天空，卻沒問那片天空會失去誰。','The sky trader bargains with Moonferry for a stormless sky, without asking who that sky might lose.'],['paperfox','交易清單上有整個港口的名字。他沒有得到大家的同意。','His trade includes every name in the harbor. He never asked their owners.'],['guide','月舟以前最討厭別人替他決定。如今他也走到了這一步，我必須親口告訴他。','Moonferry hated having his choices made for him. Now he is doing the same. I must tell him.']],
  [['thunder-ray','你們想穿過風暴，就拿一段牽掛來換。少一個在乎的人，雷聲便少一分。','Trade a bond for passage. With one less person to care about, the thunder grows quieter.'],['paperfox','那只是讓我聽不見，不是讓天空安全。我的牽掛，不是你清單上的貨物。','That would stop me hearing it, not make the sky safe. My bonds are not your cargo.'],['thunder-ray','我在風暴裏活了這麼久，當然有權選安靜！','I have lived in these storms for years. I have a right to choose quiet!'],['hero','你可以選自己的路，不能替整個港口交出名字。','You can choose your own path. You cannot surrender a whole harbor’s names.'],['guide','讓我們通過。這場風暴不是一個人付出就能停止，我們會一起找別的方法。','Let us through. One person’s sacrifice cannot settle this storm. We will seek another way together.']],
 ],ending:[['thunder-ray','交易書毀了。我以為自己只交出幾個字，卻是替別人關上整座天空。','The contract is broken. I thought I traded a few words, but was closing the sky for others.'],['dragon','斷錨順序找到了：夢根、時砂、空名、月印。先去倒懸花園。','We found the order: dreamroot, timesand, nameless seal, then moonseal. First, the Hanging Gardens.'],['guide','我已把消息送出去了。這次每一個答應幫忙的人，都知道我們在面對甚麼。','I have sent the message. This time, everyone offering help knows what we are facing.'],['paperfox','你沒有等到我們問，才說出口。這一件事，我看見了。','You told us before we had to ask. I noticed that.'],['narrator','港口回傳第一封收到的回信。風暴仍然很大，但他們終於不再只有一條孤單的航線。','The harbor sends its first reply. The storm is still vast, but their route is no longer lonely.']]},
 {number:14,summary:['花園允許人永遠留在最幸福的一天，但時間停下後，願望也無法再長大。','The garden offers a perfect day forever. When time stops, wishes cannot grow either.'],scenes:[
  [['narrator','倒懸的花園裏，花每天在同一分鐘盛開。溫室中，人們不斷重演一場完美的重逢。','Flowers bloom at the same minute each day. Inside the glasshouses, perfect reunions repeat without end.'],['tideguide','我看見古城從沒被淹沒的一天。明知道是假的，還是想在門口多站一下。','I see a day when my city never flooded. I know it is a dream, yet want to linger at the door.'],['hero','可以想念，也可以停下休息。我們不必為了繼續前進，就假裝過去不重要。','We may miss the past and pause to rest. Moving forward does not mean pretending it never mattered.']],
  [['dragon','纏根花苞會把人定在原地。看到花圈張開，先換一條路，別讓根纏住所有出口。','Root pods can hold you in place. Move out of the flower circles before the roots bind every exit.'],['paperfox','這些根沒有在吸水，正在吸走新的記憶。花園靠大家永遠重演昨天，才不會凋謝。','These roots drink new memories. The garden stays in bloom by making everyone repeat yesterday.'],['guide','如果今天都被拿走了，連紙尾剛才願意聽我說話這件事，也不會留下。','If today is taken away, even Papertail’s willingness to hear me now will be lost.']],
  [['narrator','昨日溫室擺著一張空椅，等每一個失去夥伴的人坐下。椅背刻著：「此後，不再改變。」','An empty chair invites anyone who has lost a companion. Its back reads: “Nothing will ever change again.”'],['paperfox','我終於明白父親為甚麼離開港口。他不能永遠坐在收不到信的地方，假裝那就是生活。','Now I understand why my father left the harbor. He could not spend his life beside a letter that never arrived.'],['hero','記住美好的那一天，然後把椅子留給下一次真的有人來坐。','Remember that beautiful day. Then leave the chair ready for someone who truly comes next.']],
  [['root-stag','別碰夢根。這裏讓受過傷的人，永遠得到同一個溫柔的回答。','Do not touch the dreamroot. Here, the hurt receive the same gentle answer forever.'],['tideguide','同一個回答，未必是今天需要的回答。有人想留下，也有人已經想離開。','The same answer may not be what someone needs today. Some wish to stay; others are ready to leave.'],['root-stag','離開，花便會凋謝。我又會失去一座自己照顧過的花園。','If they leave, the flowers fade. I will lose another garden I cared for.'],['guide','你照顧的是人，還是他們一直坐著的樣子？讓他們選擇，也是一種照顧。','Do you care for them, or only for the sight of them staying? Letting them choose is care too.'],['hero','我們不會燒掉昨天。但這些纏住今天的根，必須鬆開。','We will not burn yesterday. But the roots binding today must loosen.']],
 ],ending:[['root-stag','花瓣落下了……下面竟然有新的芽。我只顧守著盛開的一刻，沒有看見它們。','The petals fall… There are new shoots beneath them. I was so intent on the bloom that I never saw them.'],['dragon','第一道錨斷開。夢根留下的能量，可以送回被抽走的今天，不必再餵養機器。','The first anchor is released. Its energy can return stolen days instead of feeding the engine.'],['paperfox','雲耳，我願意再跟你一起看航圖。但信任不是回到從前，是從今天開始重新畫。','Cloud-Ear, I will share the map again. Trust is not a return to before. We must draw it anew from today.'],['guide','這次我會把每一次不知道，也寫在圖上。','This time, I will mark every uncertainty on it too.'],['narrator','空椅被搬到花園門口。想念的人仍能坐一會兒，卻不用再被一整座昨日困住。','The chair is moved to the entrance. Anyone may sit and remember without being trapped in yesterday.']]},
 {number:15,summary:['迷宮要求最完美的答案，夥伴卻選擇保留犯錯後再修正的機會。','The labyrinth demands perfection. The companions choose the chance to learn and repair instead.'],scenes:[
  [['narrator','沙漏迷宮的每塊石板，都印著他們做過的一個選擇。同一條路，時而開放，時而封死。','Every stone records a choice they once made. The same path opens, then closes again.'],['dragon','這裏在計算如果我們沒做錯，機器會不會就沒出現。可它也把當時不知道的事，算成錯誤。','It calculates whether perfect choices could have prevented the engine. It even calls unknown facts mistakes.'],['hero','我們可以回看選擇，不能假裝那時已經知道後來的一切。','We can reconsider a choice without pretending we knew the future when we made it.']],
  [['paperfox','砂時甲蟲會突然加快。看它往哪邊跑，留一個退路，不必每一擊都硬接。','Sand scarabs can suddenly rush. Watch their direction and leave an escape route instead of taking every blow.'],['guide','這塊石板問：如果我沒有去送信，月舟是不是就不必救我。','This stone asks whether Moonferry would have needed to save me if I had never delivered the letter.'],['tideguide','那封信裏也有需要被聽見的人。不能只因為後來出事，就把當時所有人的願望都刪掉。','Someone in that letter needed to be heard too. What happened later cannot erase everyone’s wishes before it.']],
  [['narrator','未來沙室出現兩道光。一道承諾永遠正確，卻只准獨自行走；另一道沒有保證，留下了夥伴的位置。','Two lights appear. One promises perfect choices, but permits only a solitary traveler. The other leaves room for companions.'],['paperfox','我以前只想找到一條不會讓父親失望的路。現在，我更想讓他知道，我真的走過哪些地方。','I once wanted a route that would never disappoint my father. Now I want him to know where I have truly been.'],['guide','我不選那條不能回頭詢問的完美路。這次我要把別人的位置，也留在我的選擇裏。','I will not choose a perfect path where I cannot ask for help. This time my choice leaves room for others.']],
  [['hourglass-sphinx','答錯的人不能前進。回到第一天，重做每一件事，直到沒有失敗。','A wrong answer cannot advance. Return to day one and repeat until there is no failure.'],['dragon','每次重做，我們也失去已經學會的東西。這不是給第二次機會，是不讓第二次發生。','Repeating erases what we learned. That does not give a second chance; it prevents one.'],['hourglass-sphinx','如果還是會犯錯，修正又有甚麼意義？','What is the point of repair if mistakes can still happen?'],['hero','意義在下一次能看見更多、問得更清楚，也知道怎樣陪做錯的人一起改。','Next time, we can notice more, ask better questions, and help someone put things right.'],['guide','請給我們下一次的路。不是替我們保證答案，是讓我們有機會一起回答。','Give us a path for next time. Not a guaranteed answer—a chance to answer together.']],
 ],ending:[['hourglass-sphinx','時砂不再倒流。你們沒有交出完美答案，卻留下了能改變答案的人。','The sand stops flowing backward. You left no perfect answer, but left people who can change their answers.'],['dragon','第二道錨鬆開了。剩下的空名印，在無名劇院。','The second anchor is released. The nameless seal is in the theater.'],['paperfox','我已寫好給父親的新信。不必等我們把一切都做好，才有資格寄出去。','I have written my father a new letter. We need not finish everything perfectly before sending it.'],['guide','我替你投遞。這次，收件人的名字會留在我手上，不會被任何面具拿走。','I will deliver it. This time, no mask will take the recipient’s name from my hands.'],['narrator','沙漏記下新的時刻。這不是最沒有錯誤的一天，卻是他們願意繼續記住的一天。','The hourglass records a new moment. Not a flawless day, but a day they choose to remember.']]},
 {number:16,summary:['無名劇院展示靜願機的成果。月舟現身，夥伴第一次看見沒有牽掛的世界。','The theater displays the engine’s results. Moonferry appears, and the companions see a world without bonds.'],scenes:[
  [['narrator','劇院燈火輝煌，觀眾每隔一分鐘就鼓掌，卻沒有人能說出自己在為誰喝采。','The theater glows. Its audience applauds every minute, but no one can name whom they are applauding.'],['paperfox','沒有哭聲、沒有爭吵……也沒有叫朋友過來一起坐的聲音。','No crying, no arguing… and no voices asking a friend to sit beside them.'],['hero','這就是靜願機說的成功？把需要回答的人，也一起變安靜了。','Is this the engine’s success? Even the people who needed an answer have fallen silent.']],
  [['narrator','失名木偶輪流扮演家人、朋友和英雄。演完後，它們把所有名字擦掉，開始下一場戲。','Nameless puppets play family, friends, and heroes. After each show, they erase the names and begin again.'],['guide','這條圍巾，是月舟教我繫的樣子。他把自己的記憶，也放進試驗裏了。','That scarf is tied as Moonferry taught me. He put his own memories into the experiment too.'],['dragon','空名印在抽取每一次相遇。把這個印關掉，至少能讓觀眾先想起自己。','The seal draws away every encounter. Closing it can help the audience remember themselves.']],
  [['moon','你們找了那麼遠，仍想把痛苦送回大家身上嗎？看看這裏，沒有一個人再被失去傷害。','You came so far to return pain to everyone? Look around. Nobody here is hurt by loss anymore.'],['guide','月舟，我回來了。你還記得，是誰教我在回信上畫藍鈴嗎？','Moonferry, I am back. Do you remember teaching me to draw a blue bell on a reply?'],['moon','……那只是投遞標記。不要再把一件普通工具，說成非要留下的牽掛。','…It was only a delivery mark. Do not turn a simple tool into a bond that must remain.'],['paperfox','你停了一下。這個名字還在，只是你一直不肯讓它說完。','You hesitated. That memory remains. You keep refusing to let it finish.']],
  [['blank-marionette','本劇禁止喚回姓名。請選一個角色，演完便可離場，任何人都不必是真的。','Names are forbidden in this play. Choose a role, perform, then leave. No one needs to be real.'],['hero','可是這裏每個座位，原本都坐過一個真正想被記得的人。','Every seat once held a real person who wanted to be remembered.'],['blank-marionette','記得，便會等待；等待，便會失望。刪去名字，是最完整的結局。','Remembering means waiting. Waiting means disappointment. Erasing the name gives a complete ending.'],['paperfox','我不替父親選結局，也不把他變成一個不會讓我失望的角色。我要寄信給真正的他。','I will not choose my father’s ending or turn him into a role that never disappoints me. My letter is for him.'],['guide','把大家的名字交還。這場戲，應該由真正站在這裏的人，決定怎樣謝幕。','Return their names. The real people standing here must choose how this play ends.']],
 ],ending:[['narrator','空名印碎開，第一位觀眾想起自己的名字，沒有立即鼓掌，而是問旁邊的人：「你還好嗎？」','The seal breaks. One audience member remembers their name, stops clapping, and asks their neighbor, “Are you all right?”'],['moon','你們還會讓彼此受傷。我等了太多次的回覆，不能再把希望放在那一聲詢問裏。','You will still hurt each other. I waited for too many replies. I cannot place my hope in that question again.'],['guide','那就先別急著相信。我會把這句話，一次一次真的問給你聽。','Then do not trust it yet. I will keep asking it, sincerely, as often as it takes.'],['dragon','月印已經移到要塞。這是最後一道錨，斷開後才能接近星橋本體。','The moonseal has moved to the fortress. It is the last anchor before Starbridge itself.'],['narrator','月舟收起面具，走進暗處。雲耳沒有追著要求他原諒，只替他保留了尚未送完的那封回信。','Moonferry retreats into shadow. Cloud-Ear does not demand forgiveness. He keeps the unfinished reply ready for him.']]},
];
