export const STORY_ACT5 = [
 {number:17,summary:['最後一道月印封住要塞。那封舊信終於完整，也讓大家找回月舟被職責蓋住的名字。','The last moonseal closes the fortress. The old letter becomes whole and reveals the name hidden beneath Moonferry’s duty.'],scenes:[
  [['narrator','月門要塞的牆上刻滿渡橋者的名字，守門人卻只准沒有牽掛的人通過。','Names cover the Moon-Gate walls, but its sentinel admits only travelers without attachments.'],['paperfox','我的新信還在。為了過一道門，就把收件人忘掉，這趟旅程便失去意義了。','My new letter is still here. Forgetting its recipient to pass a gate would undo this journey.'],['guide','我們帶著名字進來，也會帶著名字出去。','We will enter with our names, and leave with them too.']],
  [['narrator','信封街帶來的舊信，在月光下浮出被遮住的筆跡：「我不求你永遠不害怕，只求有人陪你走過。」','Moonlight reveals the old letter’s hidden words: “I do not ask you never to fear. I ask that someone walk through it with you.”'],['tideguide','後面還有署名：望川。月舟是守護者的職稱，望川才是寫信的人。','It is signed Riverwatch. Moonferry is a guardian’s title. Riverwatch is the person who wrote it.'],['guide','他總讓我在回信上畫藍鈴，自己卻只署職稱。我竟忘了問，他希望怎樣被叫住。','He taught me to draw a blue bell on replies, yet signed only his title. I never asked what he wanted to be called.']],
  [['moon-gate-knight','紀錄顯示，所有通行者都會帶來不安。月印必須一直亮著，才能保證門後沒有爭執。','Every traveler brings uncertainty. The moonseal must remain lit to guarantee peace beyond this gate.'],['dragon','那不是沒有爭執，是連提出不同想法的機會都沒有。','That is not peace. It removes the chance to disagree.'],['hero','門可以保護人，也可以讓人選擇離開。你守的是哪一種門？','A gate can protect people and let them choose to leave. Which kind do you guard?']],
  [['moon-gate-knight','我只是一名奉命留下的守衛。放你們通過，若出了錯，誰來負責？','I am a sentinel ordered to stay. If I admit you and something goes wrong, who answers for it?'],['paperfox','我們會記下各自的決定，不把所有責任推給一個守門人。','We will record our own decisions. We will not give one sentinel all the blame.'],['guide','望川當年也是這樣問的。大家讓他獨自承擔，直到他以為只有消除所有選擇，才不會再失敗。','Riverwatch asked that once. We left him alone until he thought removing every choice was the only way not to fail.'],['moon-gate-knight','承諾不足以改寫月印。請證明，你們有一起承擔的力量。','Promises cannot rewrite the seal. Show me the strength to shoulder it together.'],['hero','那就打開一道能讓答案進來的門。明天不必只有一種可能！','Then open a gate that lets an answer enter. Tomorrow can hold more than one possibility!']],
 ],ending:[['narrator','最後一道錨斷開。守門人把長槍放下，第一次親手推開那扇自己守了一年的門。','The last anchor breaks. The sentinel lowers its lance and opens the gate it has guarded for a year.'],['moon-gate-knight','我願意留下維持通道，但這次是我的選擇。把你們的名字寫在這裏吧。','I choose to keep this passage open. This time, it is my decision. Write your names here.'],['paperfox','也寫上你的。讓後來的人知道，是誰替他們開了門。','Write yours too. Let the next travelers know who opened it.'],['guide','望川，我已經找到你的名字。接下來，我要把那封回信交到你手上。','Riverwatch, I have found your name. Now I will put that reply into your hands.'],['narrator','月印退去，星橋卻露出更深的裂縫。失去四道錨的黯響，正在尋找新的聲音。','The seal fades, exposing deeper cracks in Starbridge. The unanchored Dark Echo is seeking new voices.']]},
 {number:18,summary:['黯響化成三頭巨影，重演最初的恐懼。從前被救的守護者帶著各地夥伴趕來，回應這次求救。','A three-headed echo reenacts the first fears. The rescued guardians and companions from every region answer the call.'],scenes:[
  [['narrator','通往星橋的原野，被火、霜與狂風分成三道戰線。黯響用隊長、松鼠和石像的聲音呼喊。','Fire, frost, and gale split the field before Starbridge. The echo cries out in the captain’s, squirrel’s, and guardian’s voices.'],['echo-hydra','你會失敗。沒有人會來。只有你能保護全部。','You will fail. Nobody will come. Only you can protect everything.'],['hero','這些話我們聽過，但這次，我們知道可以回答。','We have heard those words before. This time, we know they can be answered.']],
  [['puppet','晨光巡邏隊，守住退路！我不再鎖門，誰想休息，都能安全回家。','Dawn Patrol, hold the retreat! I will not lock the gate. Anyone needing rest can return safely.'],['squirrel','森林的風鈴已經把求救傳遍各地。這次，鈴聲不會被留在風裏。','The forest bells have carried the call everywhere. This time, it will not be lost in the wind.'],['paperfox','那是港口的燈，還有雨葉沼澤的船……我畫過的路，真的把大家帶來了。','Those are harbor lanterns and marsh boats… The paths I mapped really brought everyone here.']],
  [['golem','我能扶住這一段裂橋，卻不能扶住全部。渡潮，另一端拜託你。','I can brace this section, not the whole bridge. Tideway, please take the other end.'],['tideguide','收到。累了就說，我會換手。','Understood. Tell me when you tire. I will take over.'],['dragon','工坊送來新的冷卻核心。我們先測過，也把風險說清楚了。','The forge brought a new cooling core. We tested it and explained the risks first.'],['guide','原來大家不是不害怕，才願意來；是害怕，也願意問彼此需要甚麼。','They did not come because they were fearless. They came afraid, and asked what each other needed.']],
  [['echo-hydra','隊長終會倒下，風鈴終會失聲，石像終會碎裂！你們的回答，總有一天不夠！','The captain will fall, the bells go silent, the guardian shatter! One day your answer will not be enough!'],['puppet','那就今天先守好今天，明天再找新的方法。我不再用尚未發生的失敗，困住大家。','Then we guard today and seek another way tomorrow. I will not trap everyone inside a failure that has not happened.'],['squirrel','我也會再次求救。一次沒被聽見，不代表永遠沒有回答。','I will call again. One unheard call does not mean there will never be an answer.'],['hero','夥伴替我們守住路，我們替他們打開前方。三種恐懼，都不必獨自走過！','Our companions hold the path; we open the way ahead. None of these fears has to be faced alone!'],['guide','小心三個頭輪流的屬性攻擊。看清地面的警示，讓我們一步一步靠近星橋！','Watch the three heads alternate elements. Read the ground warnings, and approach Starbridge one step at a time!']],
 ],ending:[['narrator','三頭巨影散成微光。每一盞港燈、每一聲風鈴，都替裂橋留住了一小段可以行走的路。','The hydra dissolves into sparks. Every lantern and answering bell holds a small walkable section of the bridge.'],['golem','我們輪流維持橋面。沒有誰需要永遠站在同一個位置。','We will take turns supporting the bridge. Nobody must remain in one place forever.'],['paperfox','如果父親今晚看見燈，他也會知道，這裏有人等他的回信。','If Father sees the lights tonight, he will know someone here is waiting for his reply.'],['guide','望川在橋心。{hero}，陪我把最後一段路走完。','Riverwatch is at the bridge’s center. {hero}, walk the last stretch with me.'],['narrator','雲耳捧著完整的舊信踏上星橋。這次，他的身後有許多沒有被抹去的名字。','Cloud-Ear steps onto Starbridge with the whole letter. This time, many remembered names stand behind him.']]},
 {number:19,summary:['在事故發生的橋心，雲耳呼喚望川。昔日的師徒必須承認傷害，也決定今後如何同行。','At the site of the accident, Cloud-Ear calls Riverwatch by name. Mentor and pupil face the harm done and choose how to walk forward.'],scenes:[
  [['narrator','星橋仍停在事故那夜的光裏。空信袋掛在欄杆上，月舟站在當年沒有回頭的位置。','Starbridge holds the light of that night. Empty mailbags hang from the rails. Moonferry stands where he once remained behind.'],['guide','望川。這不是工作標記，也不是誰交給你的任務。我在叫你。','Riverwatch. Not a work mark or an assigned duty. I am calling you.'],['moon','那個名字……不應該還有人記得。','That name… Nobody should remember it now.']],
  [['guide','我把害怕交給面具，讓你替我留在橋上；回來後，又讓別人替我承受沒有答案的等待。','I gave my fear to the mask and left you on the bridge. Later, I made others bear the wait for answers.'],['moon','是我讓你戴上面具。我以為只要刪掉不安，你就不必重走我的路。','I offered you the mask. I thought erasing unease would spare you my path.'],['paperfox','你們都做過傷人的決定。承認它們，不會把受傷的人變成不重要，也不會讓你們只剩下錯誤。','You both made choices that hurt others. Admitting them does not dismiss the hurt, or make your mistakes your whole identity.']],
  [['narrator','紙尾把新信放在橋邊，燭鱗接通冷卻核心。每個人都留在自己能做的事情上，沒有替望川決定。','Papertail places her new letter by the bridge. Emberscale connects the cooling core. Each does what they can, without deciding for Riverwatch.'],['guide','這是你寫的舊信。我回覆得太晚，但我願意讀完整封，也聽你把話說完。','This is your old letter. My reply is late, but I will read it all and hear you finish.'],['moon','我等的不是另一個守護者……只是有人問我，今天還走得動嗎。','I was not waiting for another guardian… Only someone asking whether I could still walk today.']],
  [['moon','可是機器已經收走那麼多記憶。我若停下，所有痛苦會一起回來。你們真的還願意留下？','The engine holds so many memories. If I stop, the pain returns at once. Will you really stay?'],['hero','我們不會替所有人保證，但已經來的人會一起找方法。先讓大家取回選擇。','We cannot promise for everyone. Those here will seek a way together. First, give people their choices back.'],['moon','面具不肯解開。我親手做的規則，如今也在命令我。','The mask will not release. My own rules are commanding me now.'],['guide','望川，抓住藍鈴的聲音。{hero}，打破面具的護環，別讓黯響把他的話吞掉！','Riverwatch, hold onto the blue bell’s sound. {hero}, break the mask’s rings before the echo swallows his words!'],['moon','那就讓我看見……我可以不再獨自守在這裏。','Then let me see… that I do not have to guard this place alone anymore.']],
 ],ending:[['narrator','面具裂開。望川的原印與雲耳的藍鈴響起同一段旋律，橋上的夜色第一次向後退去。','The mask cracks. Riverwatch’s original seal and Cloud-Ear’s blue bell ring the same melody. The night on the bridge recedes.'],['moon','雲耳，我今天很累。我想坐下來，也想看看你們帶來的那封新信。','Cloud-Ear, I am tired today. I want to sit down, and see the new letter you brought.'],['guide','坐在這裏吧。等你休息好，我們一起投遞。','Sit here. When you have rested, we will deliver it together.'],['dragon','核心仍在自行運轉。停下它的人不必留下接替守護者——我們會從橋外同步拆掉回路。','The core is running on its own. Whoever stops it need not become its guardian. We will dismantle its circuits from outside.'],['hero','最後一段交給我們。望川，請把願望交還給大家，也把休息的時間留給自己。','We will take the last stretch. Riverwatch, return the wishes, and keep some time to rest.'],['narrator','星心庭門打開。這次沒有誰被留在身後，只有各自願意做出的回答。','The Starheart Court opens. This time no one is left behind. Each person chooses their answer.']]},
 {number:20,summary:['黯響之心守著最後的記憶。眾人共同解除靜願機，讓願望、名字與未來回到每個人手中。','The Echo Heart holds the final memories. Together, the companions dismantle the engine and return wishes, names, and futures to their owners.'],scenes:[
  [['narrator','星心庭裏升起晶翼巨影。它沒有主人，只有一條不斷重複的命令：不准任何人再受傷。','A crystal-winged shadow rises in Starheart Court. It has no master, only a repeating order: no one may ever be hurt again.'],['echo-heart','只要沒有記憶，便沒有失去。只要沒有願望，便沒有失敗。','Without memory there is no loss. Without wishes there is no failure.'],['hero','記憶裏也有擁抱，願望裏也有明天。你不能為了刪掉一部分，就拿走全部。','Memory holds embraces too. Wishes hold tomorrow. You cannot remove everything to erase one part.']],
  [['dragon','第一道回路已斷。各地傳來確認：名字正在回到紀錄裏。','The first circuit is cut. The regions confirm that names are returning to their records.'],['tideguide','潮城的居民自己選擇取回記憶。我們有人陪伴他們，不會催促大家立刻開心。','The city’s people are choosing to reclaim their memories. We have company ready for them. No one is rushed to be happy.'],['paperfox','第二道由我與守燈者負責。這張地圖現在寫著每個願意幫忙的人，也寫著換手的時間。','The beacon keeper and I have the second. My map names each volunteer, and when someone takes their place.']],
  [['moon','最後的原印已經放回。舊制度需要一個人永遠留下，我把那條命令撤銷了。','The original seal is restored. The old system demanded one person stay forever. I have revoked that order.'],['guide','以後有人累了，可以離開、休息，再決定要不要回來。守護不是失去自己的名字。','Anyone tired may leave, rest, and choose whether to return. Protecting others must not erase your name.'],['hero','夥伴們都準備好了。剩下的黯響，就讓我們替大家打散！','Our companions are ready. We will scatter the echo that remains!']],
  [['echo-heart','回答終會停止。你們終會孤單。把未來交給我，便不必再等待！','Answers will stop. You will be alone. Give me the future, and never wait again!'],['paperfox','父親也許不會在今天回來，但這封信有我的名字，有我真正想說的話。我願意寄出去。','Father may not return today. This letter holds my name and what I truly want to say. I choose to send it.'],['moon','我曾以為等待只有痛苦。現在，我想把下一封回信留給自己讀。','I thought waiting held only pain. Now I want to stay to read the next reply.'],['guide','小心火、霜、雷與風的變化！看地面警示，避開攻擊，再把每一次命中化成向前的力量！','Watch fire, frost, lightning, and gale! Read the warnings, evade, and turn each hit into strength to advance!'],['hero','每個願望，都應該由自己的主人決定。讓星光回到大家身邊！','Every wish belongs to its own keeper. Let the starlight return to everyone!']],
 ],ending:[['narrator','最後一道護環碎開，黯響之心化成無數柔和星點。記憶沿著二十段旅途，回到原來的主人身邊。','The final ring shatters. The Echo Heart becomes gentle sparks. Memories travel the twenty-part journey back to their owners.'],['golem','星晶重新亮起，卻不再把所有願望收藏在一處。它把求救的聲音傳出去，也把回答帶回來。','The crystal shines without locking wishes away. It carries calls for help outward, and brings answers home.'],['puppet','晨光訓練場開門了。今天有練習，也有休息，大家可以自己選。','The Dawn Training Grounds are open. There is training and rest today. Everyone may choose.'],['squirrel','風鈴換了新繩。第一個聽到求救的人，會叫上別人一起幫忙。','The bells have new cords. Whoever hears a call first will invite others to help.'],['dragon','我在工坊加了一張長桌。每件新發明，要先聽使用它的人怎樣想。','I added a long table to the forge. Every invention begins with the people who will use it.'],['tideguide','潮城開始重新寫歷史。空白的那一年也留下來，提醒我們曾經忘記，後來又選擇記住。','The city is writing its history again. The blank year remains, reminding us we once forgot, then chose to remember.'],['paperfox','港口收到父親的回信了！他在另一岸修橋，要沿我畫的路回來。他問我，可不可以一起畫下一張。','Father’s reply arrived! He is repairing bridges across the sea and will return along my route. He asks if we can draw the next map together.'],['guide','我把你的新信送出去了，也會把回覆親手交給你。這次不只在紀錄上寫「投遞完成」。','I delivered your new letter, and will put the reply in your hands. This time it is more than a record marked “Delivered.”'],['moon','今天我叫望川，不用替所有人守夜。我想和雲耳走一條沒有任務的路，看看晨光。','Today I am Riverwatch. I need not watch for everyone all night. I want to walk with Cloud-Ear without a task, and see the dawn.'],['hero','一路上，我們救過別人，也被別人救過。原來一起發光，就是把這些回答交還給彼此。','We saved others and were saved ourselves. Shining together means returning those answers to one another.'],['narrator','藍鈴輕輕響起。紙尾的新地圖上，二十個地方都有名字，也都有一條通往家的路。','The blue bell rings softly. Papertail’s new map names all twenty places, each with a road leading home.'],['narrator','《失落的星光》完。願你害怕時有人同行，等待時有人回覆，也永遠保有替自己選擇的名字。','The Lost Starlight · The End. May someone walk with you in fear, answer you in waiting, and let your name remain your own.']]},
];
