import Phaser from 'phaser';
import './brawl.css';
import './adventure.css';
import './adventure-acts.css';
import {ADVENTURE,STORY_REVISION,chapterByStage,chapterScenes,pendingStory,restoreStoryProgress,storyText,type StoryScene,type StoryChapter,type StoryProgress} from '../../lib/brawl/story.mjs';
import {api} from '../api';import {audio} from '../audio';
import {INPUT as I,VERSION,SUPPORTED_VERSIONS,FIGHTERS,STAGES,fightersForVersion,combatFighterById} from '../../lib/brawl/catalog.mjs';
import {createBattle,stepBattle,replayBattle,battleResult,type BattleState,type BattleOptions,type InputFrame} from '../../lib/brawl/simulation.mjs';
import type {Bootstrap,Identity,Locale} from '../types';
import type {BrawlCatalog,BrawlProgress,BrawlRun,StoredBattle,BrawlReceipt} from './types';
import {skillState} from './skillState';
import {BattleInput} from './input';import {BattleScene} from './BattleScene';
import {lockGameBrowserInteractions} from '../game/GameBrowserInteractions';
import {loadBattle,saveBattle,clearBattle} from './session';
import type {PvPClient,DuelSession,DuelFrame} from './pvp-client';
import type {RankedOverview} from './ranking-types';
import {rankSummary,rankLeaderboard,rankBadge,rankName,rankTermsText} from './ranking-ui';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class BrawlController {
  private accessLocked=false;
  setAccessLocked(locked:boolean){if(this.accessLocked===locked)return;this.accessLocked=locked;if(locked){this.pause();this.input?.clear();void this.persist();}else if(this.battle&&!this.settled){this.paused=true;this.pause();}}
  private root:HTMLElement;private catalog!:BrawlCatalog;private progress!:BrawlProgress;private stored?:StoredBattle;private run?:BrawlRun;private battle?:BattleState;private input?:BattleInput;private inputs:InputFrame[]=[];private lastMask=0;private paused=true;private ready=false;private disposed=false;private finishing=false;private timer?:number;private finishKey:string=crypto.randomUUID();private selected=FIGHTERS[0].id;private mode='campaign';private abort=new AbortController();private saveQueue=Promise.resolve();private settled=false;private busy=false;
  private adventureAct=0;
  private storyProgress:StoryProgress={revision:STORY_REVISION,seen:[]};
  private story?:{scene:StoryScene;chapter:StoryChapter;index:number;review:boolean};
  private online?:DuelSession;private networkTimer?:number;
  private ranking?:RankedOverview;
  private rankingLoading=false;
  private leaderboardExpanded=false;
  private get liveMode(){return this.mode==='pvp'||this.mode==='ranked';}
  private releaseBrowserInteractions?:()=>void;
  get onlineId(){return this.online?.match.id;}
  get localBusy(){return !!this.battle&&!this.online&&!this.settled;}
  private difficulty='easy';private opponent=FIGHTERS[0].id;private rosterFilter='owned';private rosterScroll=0;
  constructor(private game:Phaser.Game,private identity:Identity,private bootstrap:()=>Bootstrap,private refresh:()=>Promise<void>,private shop:()=>void,private pvp?:PvPClient){this.root=document.createElement('div');this.root.className='brawl-layer';this.root.id='brawl-root';document.querySelector('#playSurface')!.append(this.root);document.querySelector('.pet-shell')?.classList.add('brawl-open');const signal=this.abort.signal;
    window.addEventListener('keydown',event=>this.storyKeyboard(event),{signal,capture:true});
    this.root.addEventListener('click',event=>{const b=(event.target as HTMLElement).closest<HTMLElement>('[data-brawl]');if(b)void this.action(b).catch(error=>this.notice(error.message));},{signal});
    this.root.addEventListener('change',event=>{const select=event.target as HTMLSelectElement;if(select.id==='brawlMusic'||select.id==='brawlSfx'){audio.setLevels(Number(this.root.querySelector<HTMLInputElement>('#brawlMusic')!.value),Number(this.root.querySelector<HTMLInputElement>('#brawlSfx')!.value));}else if(select.id==='brawlDifficulty'){this.difficulty=select.value;this.updateStartButtons();}else if(select.id==='brawlOpponent')this.opponent=select.value;},{signal});
    document.addEventListener('visibilitychange',()=>{if(document.hidden){this.pause();void this.persist();}},{signal});window.addEventListener('pagehide',()=>{this.pause();void this.persist();},{signal});window.addEventListener('online',()=>{if(this.battle&&['won','lost'].includes(this.battle.status)&&this.run&&!this.settled)void this.finish();},{signal});window.addEventListener('resize',()=>{if(window.innerHeight>window.innerWidth&&this.battle)this.pause();},{signal});
    this.pvp?.addEventListener('change',()=>{if(!this.battle&&this.liveMode)this.renderPeers();if(this.online)this.networkStatus();},{signal});
    this.pvp?.addEventListener('frame',event=>this.receiveFrame((event as CustomEvent<DuelFrame>).detail),{signal});
    this.pvp?.addEventListener('result',event=>this.onlineResult((event as CustomEvent).detail),{signal});
  }
  private get locale():Locale{return this.identity.language||'zh-HK';}
  private t(zh:string,en:string){return this.locale==='zh-HK'?zh:en;}
  private name(value:{'zh-HK':string;'en-US':string}){return value[this.locale];}
  async open(){
    this.root.innerHTML=`<div class="brawl-loading">${this.t('正在準備大廳…','Preparing the lobby…')}</div>`;
    try{const [catalog,progress,stored,ranking]=await Promise.all([api.brawlCatalog(),api.brawlProgress(),loadBattle(this.identity.id).catch(()=>undefined),api.brawlRanking().catch(()=>undefined)]);if(this.disposed)return;this.catalog=catalog;this.progress=progress;this.ranking=ranking;this.stored=stored&&SUPPORTED_VERSIONS.includes(stored.version)&&stored.studentId===this.identity.id&&Date.parse(stored.run.expiresAt)>Date.now()?stored:undefined;const owned=this.bootstrap().pets.filter(p=>catalog.fighters.some(f=>f.id===p.speciesId));const nextStage=catalog.stages.findIndex((stage,index)=>index===0?!Object.keys(progress.best).some(k=>k.startsWith(stage.id+':')):Object.keys(progress.best).some(k=>k.startsWith(catalog.stages[index-1].id+':'))&&!Object.keys(progress.best).some(k=>k.startsWith(stage.id+':')));this.adventureAct=Math.floor(Math.max(0,nextStage)/4);this.selected=owned.find(p=>p.id===this.bootstrap().profile.activePetId)?.speciesId||owned[0]?.speciesId||this.selected;this.lobby();}
    catch(error){if(!this.disposed){this.root.className='brawl-layer brawl-lobby';this.root.innerHTML=`<div class="brawl-lobby-content"><h1>${this.t('大廳未能載入','The lobby could not load')}</h1><p>${esc((error as Error).message)}</p><button class="primary" data-brawl="load">${this.t('重新載入','Retry')}</button><div class="brawl-notice" role="status"></div></div>`;}throw error;}
  }
  private lobby(){if(this.disposed)return;this.stopScene();this.battle=undefined;this.pvp?.setBusy(false);this.root.className='brawl-layer brawl-lobby'+(this.liveMode?' brawl-pvp-lobby':'');document.querySelector('.pet-shell')?.classList.remove('brawl-active');const owned=this.bootstrap().pets;const zh=this.locale==='zh-HK';
    this.root.innerHTML=`<div class="brawl-lobby-content"><header class="brawl-heading"><div><p class="brawl-eyebrow">PET BRAWL · ADVENTURE CLUB</p><h1>${this.t('小小寵物，大大冒險','Little pets. Big adventures.')}</h1><p>${this.t('帶上你的夥伴，走位、連招，迎戰森林守護者。','Take your companion into the arena. Move, combine attacks, and face the forest guardians.')}</p></div><div class="brawl-daily"><span>✦</span><b>${this.liveMode?(this.mode==='ranked'?'100–500':'500'):this.mode==='leaderboard'?this.ranking?.self.dailyCoins??0:this.progress.rewardsRemaining+' / 3'}</b><small>${this.liveMode?this.t('每人入場費 · 接受後扣款','Entry per player · paid after acceptance'):this.mode==='leaderboard'?this.t('目前級別 · 每日自動金幣','Current tier · automatic daily coins'):this.t('今日可領勝利獎勵','Rewarded wins left today')}</small></div></header>
      ${this.stored||this.progress.activeRun?`<div class="brawl-resume"><span>${this.t('上次冒險仍在等待你','Your last adventure is waiting')}</span>${this.stored?`<button data-brawl="resume" class="primary">${this.t('繼續冒險','Continue')}</button>`:''}<button data-brawl="abandon" class="secondary">${this.t('放棄上次','Abandon run')}</button></div>`:''}
      <div class="brawl-mode-tabs">${[['campaign','冒險','Adventure'],['tutorial','學習操作','Learn'],['practice','練習場','Practice'],['duel','AI 對戰','AI duel'],['pvp','自由對戰','Free duel'],['ranked','排名對戰','Ranked duel'],['leaderboard','排行榜','Leaderboard']].map(([id,z,e])=>`<button data-brawl="mode" data-id="${id}" class="${this.mode===id?'selected':''}">${zh?z:e}</button>`).join('')}</div>
      ${this.mode==='campaign'?`<section class="brawl-adventure-intro"><span aria-hidden="true">✦</span><div><h2>${esc(this.name(ADVENTURE.title))}</h2><p>${esc(this.name(ADVENTURE.premise))}</p></div></section>`:''}
      ${this.mode==='leaderboard'?rankLeaderboard(this.ranking,this.locale,this.leaderboardExpanded):`${this.mode==='ranked'?rankSummary(this.ranking,this.locale):''}${this.roster(owned)}
      ${!this.liveMode&&this.catalog.fighters.find(f=>f.id===this.selected)?.skills.some(k=>k.description)?`<p class="brawl-kit-note">${this.catalog.fighters.find(f=>f.id===this.selected)!.skills.map((k,n)=>`${n===0?'U':'I'} · <b>${esc(this.name(k.name))}</b>：${esc(k.description?this.name(k.description):'')}`).join('<br>')}</p>`:''}
      ${!this.liveMode?`<div class="brawl-stage-head"><h2>${this.mode==='campaign'?this.t('選擇下一站','Choose your next stop'):this.t('準備出發','Ready to play')}</h2><label>${this.t('難度','Difficulty')}<select id="brawlDifficulty"><option value="easy">${this.t('輕鬆','Easy')}</option><option value="normal">${this.t('標準','Normal')}</option><option value="hard">${this.t('挑戰','Hard')}</option></select></label>${this.mode==='duel'?`<label>${this.t('對手','Opponent')}<select id="brawlOpponent">${this.catalog.fighters.map(f=>`<option value="${f.id}">${esc(this.name(f.name))}</option>`).join('')}</select></label>`:''}</div>
      <nav class="brawl-act-tabs" aria-label="${this.t('冒險篇章','Adventure acts')}">${ADVENTURE.acts.map((act,n)=>`<button data-brawl="act" data-id="${n}" class="${n===this.adventureAct?'selected':''}" aria-pressed="${n===this.adventureAct}"><b>${n+1}</b><span>${esc(this.name(act))}<small>${n*4+1}–${n*4+4} · ${this.t('章','Chapters')}</small></span></button>`).join('')}</nav><div class="brawl-stage-grid brawl-adventure-grid">${this.catalog.stages.map((s,index)=>{if(Math.floor(index/4)!==this.adventureAct)return '';const unlocked=this.mode!=='campaign'||index===0||Object.keys(this.progress.best).some(k=>k.startsWith(this.catalog.stages[index-1].id+':'));const has=owned.some(p=>p.speciesId===this.selected),stars=Math.max(0,...Object.entries(this.progress.best).filter(([k])=>k.startsWith(s.id+':')).map(([,v])=>v.stars));return `<article class="brawl-stage-card"><img src="${esc(this.catalog.assets?.backgrounds[s.id])}" alt=""><div><p class="brawl-eyebrow">${this.mode==='campaign'?` ${String(index+1).padStart(2,'0')} · ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}`:this.t('自由練習 · 不發養成獎勵','Free play · no raising rewards')}</p><h3>${esc(this.name(this.mode==='campaign'?chapterByStage(s.id)!.title:s.name))}</h3><p>${esc(this.name(this.mode==='campaign'?chapterByStage(s.id)!.summary:s.subtitle))}</p>${this.mode==='campaign'?`<ol class="brawl-chapter-sections">${chapterByStage(s.id)!.sections.map((section,n)=>`<li><b>${n+1}</b>${esc(this.name(section.title))}${n===3?' · Boss':''}</li>`).join('')}</ol>`:''}<button data-brawl="start" data-stage="${s.id}" ${!unlocked||!this.catalog.enabled||!has?'disabled':''}>${!unlocked?this.t('先完成前一關','Clear the previous stage'):!has?this.t('需要擁有這隻寵物','Own this fighter first'):this.t('出發 →','Let’s go →')}</button>${this.mode==='campaign'&&stars>0?`<button class="brawl-story-review" data-brawl="story-review" data-stage="${s.id}">${this.t('故事回顧','Review story')}</button>`:''}</div></article>`;}).join('')}</div>`:this.onlinePanel()}
      ${!owned.some(p=>p.speciesId===this.selected)?`<p class="brawl-note">${this.t('所有模式都需要擁有這隻角色。請先到寵物樂園商店購買。','Own this fighter in Pet Paradise before using it in any mode.')} <button data-brawl="shop">${this.t('前往商店','Visit shop')}</button></p>`:''}
      `}
      <p class="brawl-note">${this.liveMode||this.mode==='leaderboard'?'':this.t('冒險免費入場 · 每日三次勝利獎勵，各 5 金幣＋最多 10 XP · 每關一次免費波次重試','Adventure entry is free · first 3 daily wins: 5 coins + up to 10 XP each · one wave retry per adventure')}</p><div class="brawl-notice" role="status"></div></div>`;
    const roster=this.root.querySelector<HTMLElement>('.brawl-fighters');if(roster)roster.scrollTop=this.rosterScroll;
    const difficultySelect=this.root.querySelector<HTMLSelectElement>('#brawlDifficulty');if(difficultySelect)difficultySelect.value=this.difficulty;const opponent=this.root.querySelector<HTMLSelectElement>('#brawlOpponent');if(opponent)opponent.value=this.opponent;this.updateStartButtons();
    if(this.liveMode)this.renderPeers();
    if(!this.catalog.enabled)this.notice(this.t('大亂鬥暫時未開放，請稍後再來。','Pet Brawl is temporarily unavailable.'));
  }
  private roster(owned:Bootstrap['pets']){
    const cards=this.catalog.fighters.filter(f=>this.rosterFilter==='all'||owned.some(p=>p.speciesId===f.id)===(this.rosterFilter==='owned'));
    return `<div class="brawl-roster-head"><b>${this.t('選擇夥伴','Choose a fighter')} · ${this.catalog.fighters.length}</b><div class="brawl-roster-filters">${[['owned','已擁有','Owned'],['all','全部','All'],['locked','未擁有','Locked']].map(([id,z,e])=>`<button data-brawl="filter" data-id="${id}" aria-pressed="${this.rosterFilter===id}" class="${this.rosterFilter===id?'selected':''}">${this.t(z,e)}</button>`).join('')}</div></div><div class="brawl-fighters" tabindex="0" aria-label="${this.t('寵物角色清單','Fighter roster')}">${cards.map(f=>{
      const pet=owned.find(p=>p.speciesId===f.id),definition=this.bootstrap().catalog.pets.find(p=>p.id===f.id),rarity=f.rarity||'common';
      return `<button class="brawl-fighter ${this.selected===f.id?'selected':''} ${pet?'':'locked'} rarity-${rarity}" aria-pressed="${this.selected===f.id}" data-brawl="fighter" data-id="${f.id}"><span class="brawl-owned">${pet?this.t('已擁有','Owned'):this.t('未擁有 · 需購買','Locked · purchase first')}</span><span class="brawl-rarity">${this.t(rarity==='epic'?'史詩':rarity==='rare'?'稀有':'普通',rarity==='epic'?'Epic':rarity==='rare'?'Rare':'Common')}</span><img loading="lazy" src="${esc(definition?.art[0])}" alt="${esc(this.name(f.name))}"><h2>${esc(this.name(f.name))}</h2><p>${esc(this.name(f.role))}</p><div class="brawl-skill-names">${f.skills.map(k=>`<span data-element="${esc(String(k.element||''))}" title="${esc(this.elementName(k.element))}">${k.element?esc(this.elementName(k.element))+' · ':''}${esc(this.name(k.name))}</span>`).join('')}</div><small>HP ${f.hp} · ${this.t('初階戰鬥造型','Base battle form')}</small></button>`;
    }).join('')||`<p class="brawl-roster-empty">${this.t('沒有符合篩選的角色。可選「全部」查看並前往商店購買。','No matching fighters. Select All to browse and visit the shop.')}</p>`}</div>`;
  }
  private updateStartButtons(){
    for(const button of this.root.querySelectorAll<HTMLButtonElement>('[data-brawl="start"]')){
      const stage=button.dataset.stage!,index=this.catalog.stages.findIndex(s=>s.id===stage);
      const previous=index===0||Object.keys(this.progress.best).some(k=>k.startsWith(this.catalog.stages[index-1].id+':'));
      const hard=this.difficulty!=='hard'||!!this.progress.best[stage+':normal'];
      const owned=this.bootstrap().pets.some(p=>p.speciesId===this.selected);
      const message=this.mode==='campaign'&&!previous?this.t('先完成前一關','Clear the previous stage'):this.mode==='campaign'&&!hard?this.t('先完成標準難度','Clear Normal first'):!owned?this.t('需要擁有這隻寵物','Own this fighter first'):undefined;
      button.disabled=!this.catalog.enabled||!!message;button.textContent=message||this.t('出發 →','Let’s go →');
    }
  }
  private async refreshRanking(render=true){
    if(this.rankingLoading)return;this.rankingLoading=true;
    try{this.ranking=await api.brawlRanking();await this.refresh();if(!this.disposed&&!this.battle&&render)this.lobby();}
    catch(error){if(!this.disposed)this.notice((error as Error).message);}
    finally{this.rankingLoading=false;}
  }
  private onlinePanel(){return `<section class="pvp-panel"><div class="pvp-panel-head"><div><h2>${this.t('邀請在線同學','Invite an online student')}</h2><p>${this.mode==='ranked'?this.t('同級每人 500 金幣，每差一級減 100，最低 100；接受後才扣款。','500 coins each at the same tier, 100 less per tier gap, minimum 100. Charged after acceptance.'):this.t('對方接受後，雙方各付 500 金幣。拒絕、取消或逾時均不扣款。','Both students pay 500 coins after acceptance. Declining, cancellation and expiry cost nothing.')}</p></div><label>${this.t('對戰場地','Arena')}<select id="pvpStage" class="pvp-stage-select">${this.catalog.stages.map(s=>`<option value="${s.id}">${esc(this.name(s.name))}</option>`).join('')}</select></label></div>${this.mode==='ranked'?`<p class="ranked-rule">${rankBadge(this.pvp?.self?.rank.tier??this.ranking?.self.tier??0,this.locale)} ${this.t('同級勝 +5／負 −5 分；低級勝高級，每差一級多取 2 分；高級勝低級，每差一級少取 1 分。敗方扣同等分數，最低 0 分，不降級。','Same-tier wins +5 / losses −5. An underdog win earns 2 more per tier gap; a favorite win earns 1 less per tier gap. The loser deducts the same amount. Minimum 0 points, no demotion.')}</p>`:''}<div id="pvpPeers" class="pvp-online-list"></div><p class="pvp-panel-note">${this.mode==='ranked'?this.t('90 秒一局 · 可跨級挑戰 · 銅／銀／金／鑽享每日自動金幣','90-second matches · cross-tier challenges · daily coins from Bronze through Diamond'):this.t('使用自己的寵物 · 90 秒一局 · 自由對戰不影響排名','Use your own pet · 90-second duel · free duels do not affect rankings')}</p></section>`;}
  private renderPeers(){const target=this.root.querySelector('#pvpPeers');if(!target)return;const owned=this.bootstrap().pets.some(p=>p.speciesId===this.selected),balance=this.bootstrap().wallet.balance,pending=this.pvp?.invitation?.status==='pending';
    if(!this.pvp?.connected){target.innerHTML=`<p class="pvp-empty">${this.t('正在連接在線同學…','Connecting to online students…')}</p><button class="secondary" data-brawl="pvp-connect">${this.t('重新連接','Reconnect')}</button>`;return;}
    if(!this.pvp.peers.length){target.innerHTML=`<p class="pvp-empty">${this.t('暫時沒有其他同學在寵物樂園在線。','No other students are online in Pet Paradise right now.')}</p>`;return;}
    target.innerHTML=this.pvp.peers.map(p=>{const ranked=this.mode==='ranked',terms=ranked?p.rankTerms:undefined,fee=terms?.fee||500,unknown=ranked&&!terms;const message=unknown?this.t('更新排名中…','Updating rank…'):!owned?this.t('需要擁有此寵物','Own this fighter first'):balance<fee?this.t(`需要 ${fee} 金幣`,`Need ${fee} coins`):pending?this.t('等待邀請回覆','Awaiting a reply'):!p.available?this.t(p.hasFighter?'遊戲中／待回覆':'暫無出戰寵物',p.hasFighter?'Busy / invited':'No fighter'):this.t(`${ranked?'邀請排名對戰':'邀請對戰'} · ${fee}`,`${ranked?'Ranked invite':'Invite'} · ${fee}`);return `<article class="pvp-online-row"><span class="pvp-status-dot ${p.available?'':'busy'}"></span><div class="pvp-peer-info"><b>${esc(p.name)}</b><small>${esc(p.className)} · ${this.t(p.available?'在線':'暫時未能接受邀請',p.available?'Online':'Currently unavailable')}</small>${terms?`<small class="pvp-peer-terms">${rankTermsText(terms,0,this.locale)}</small>`:''}</div>${ranked?rankBadge(p.rank?.tier??0,this.locale):''}<button data-brawl="invite" data-target="${esc(p.id)}" ${unknown||!owned||balance<fee||pending||!p.available||!this.catalog.enabled?'disabled':''}>${message}</button></article>`;}).join('');
  }
  openOnline(session:DuelSession){if(this.disposed)return;this.online=session;this.run=undefined;this.battle=structuredClone(session.state);this.mode=session.match.mode==='ranked'?'ranked':'pvp';this.inputs=[];this.lastMask=0;this.play(false);}
  reconnectOnline(){if(this.online&&this.ready)void this.pvp?.ready().catch(e=>this.notice(e.message));}
  private receiveFrame(frame:DuelFrame){if(!this.online||!this.battle||frame.matchId!==this.online.match.id)return;Object.assign(this.battle,frame.state);this.online.phase=frame.phase;this.online.startAt=frame.startAt;(this.game.scene.getScene('Brawl') as BattleScene)?.receiveEvents(frame.events,frame.state.tick);this.updateHud();this.networkStatus();}
  private networkStatus(){if(!this.online||!this.battle)return;const phase=this.pvp?.connected?this.pvp.session?.phase||this.online.phase:'reconnecting';let text='',detail='';
    if(phase==='preparing'){text=this.t('等待雙方準備','Preparing both fighters');detail=this.t('未能開場會退回雙方入場費','Both fees are refunded if the duel cannot start');}
    else if(phase==='countdown'){text=String(Math.max(1,Math.ceil(((this.pvp?.session?.startAt||0)-Date.now())/1000)));detail=this.t('準備對戰！','Get ready!');}
    else if(phase==='reconnecting'){text=this.t('等待重新連線','Waiting for reconnection');detail=this.t('對戰暫停，請保持本頁開啟','Duel paused. Keep this page open');this.pvp?.input(0,true);}
    else if(phase==='settling'){text=this.t('正在確認對戰結果…','Confirming the duel result…');}
    const existing=this.root.querySelector('.pvp-wait');if(text){if(existing)existing.innerHTML=`${esc(text)}<small>${esc(detail)}</small>`;else{const e=document.createElement('div');e.className='pvp-wait';e.setAttribute('role','status');e.innerHTML=`${esc(text)}<small>${esc(detail)}</small>`;this.root.append(e);}}else existing?.remove();
    const hint=this.root.querySelector('#brawlHint');if(hint&&!this.paused)hint.textContent='';
  }
  private onlineResult(result:{match:DuelSession['match'];winnerIndex:number|null;refunded:boolean}){if(!this.online||result.match.id!==this.online.match.id)return;this.online.match=result.match;this.online.phase=result.match.status;this.paused=true;this.settled=true;this.input?.clear();this.root.querySelector('.pvp-wait')?.remove();const win=result.winnerIndex===this.online.playerIndex,cancelled=result.match.status==='cancelled';const rank=result.match.rankResults?.find(r=>r.studentId===this.identity.id);const rankContent=rank?`<div class="rank-result">${rankBadge(rank.tier,this.locale)}${rank.pointsDelta!=null?`<b class="${rank.pointsDelta<0?'rank-delta-loss':'rank-delta-win'}">${rank.pointsDelta>0?'+':''}${rank.pointsDelta} ${this.t('分','points')}</b>`:''}${rank.promoted?`<b>${this.t('晉級成功！','Promotion achieved!')}</b>`:''}<small>${rank.pointsToPromote?this.t(`此級別 ${rank.points} / ${rank.pointsToPromote} 分，再獲 ${rank.pointsToPromote-rank.points} 分可晉級。`,`${rank.points} / ${rank.pointsToPromote} points here; ${rank.pointsToPromote-rank.points} more to promote.`):this.t(`已達最高的鑽級！積分 ${rank.points}。`,`Diamond tier! ${rank.points} points.`)} · ${this.t('勝率','Win rate')} ${rank.winRate}% · ${rank.games} ${this.t('場','played')}</small>${rank.promotionCoins?`<b>+${rank.promotionCoins} ${this.t('金幣 · 今日級別獎勵已入帳','coins · today’s tier reward credited')}</b>`:''}</div>`:'';
    this.modal(cancelled?this.t('對戰已取消','Duel cancelled'):win?this.t('對戰勝利！','Duel victory!'):result.winnerIndex===null?this.t('勢均力敵','A draw'):this.t('下次再挑戰！','Try again soon!'),`<p>${result.refunded?this.t(`雙方的 ${result.match.fee} 金幣入場費已退回。`,`Both ${result.match.fee}-coin entry fees were refunded.`):result.match.mode==='ranked'?this.t('入場費已支付。排名結果已記錄。','Entry fees were paid. Your ranked result is recorded.'):this.t('入場費已支付。對戰結果不另發金幣或 XP。','Entry fees were paid. The result does not grant extra coins or XP.')}</p>${rankContent}<button class="primary" data-brawl="again">${this.t('返回對戰大廳','Back to duel lobby')}</button>`);void this.refresh().catch(()=>{});
  }
  private async action(button:HTMLElement){const id=button.dataset.brawl;if(this.busy||this.accessLocked)return;await audio.unlock();
    if(id==='load')await this.open();else if(id==='act'){this.adventureAct=Math.max(0,Math.min(4,Number(button.dataset.id)||0));this.lobby();}else if(id==='mode'){if(this.mode===button.dataset.id)return;this.mode=button.dataset.id!;if(this.mode==='ranked'||this.mode==='leaderboard')await this.refreshRanking(false);if(!this.battle)this.lobby();}else if(id==='fighter'){this.rosterScroll=this.root.querySelector('.brawl-fighters')?.scrollTop||0;this.selected=button.dataset.id!;this.lobby();}else if(id==='filter'){this.rosterFilter=button.dataset.id!;this.rosterScroll=0;this.lobby();}
    else if(id==='rank-expand'){const content=this.root.querySelector<HTMLElement>('.brawl-lobby-content'),scroll=content?.scrollTop||0;this.leaderboardExpanded=!this.leaderboardExpanded;this.lobby();const updated=this.root.querySelector<HTMLElement>('.brawl-lobby-content');if(updated)updated.scrollTop=scroll;this.root.querySelector<HTMLButtonElement>('[data-brawl="rank-expand"]')?.focus({preventScroll:true});}else if(id==='rank-refresh')await this.refreshRanking();else if(id==='pvp-connect')await this.pvp?.start();else if(id==='invite'){const pet=this.bootstrap().pets.find(p=>p.speciesId===this.selected);if(!pet||!this.pvp)throw new Error(this.t('請選擇自己擁有的出戰寵物。','Choose a fighter you own.'));if(innerHeight>innerWidth)throw new Error(this.t('請先轉為橫向。','Rotate to landscape first.'));await this.pvp.invite(button.dataset.target!,pet.id,this.root.querySelector<HTMLSelectElement>('#pvpStage')!.value,crypto.randomUUID(),this.mode==='ranked'?'ranked':'friendly');}
    else if(id==='pvp-leave'){this.paused=true;this.input?.clear();await this.pvp?.leave();}
    else if(id==='start'){this.busy=true;try{await this.start(button.dataset.stage!);}finally{this.busy=false;if(!this.battle)this.pvp?.setBusy(false);}}
    else if(id==='story-next')this.moveStory();else if(id==='story-back')this.moveStory(true);else if(id==='story-review'||id==='story-review-scene')this.reviewStory(button.dataset.stage!,button.dataset.scene);
    else if(id==='resume'){if(this.stored){await api.brawlAccess({petId:this.stored.run.petId,fighterId:this.stored.run.options.fighterId!,mode:'campaign'});this.run=this.stored.run;this.finishKey=this.stored.finishKey;this.inputs=this.stored.inputs.map(f=>({...f}));this.battle=replayBattle({...this.run.options,version:this.stored.version},this.inputs,this.stored.endTick,{terminal:false});this.lastMask=this.inputs.at(-1)?.mask||0;const chapter=chapterByStage(this.battle.stageId);this.storyProgress=chapter?restoreStoryProgress(chapter,this.battle,this.stored.story):{revision:STORY_REVISION,seen:[]};this.play(true);}}
    else if(id==='abandon'){this.busy=true;try{const run=this.progress.activeRun||this.stored?.run;if(run)await api.brawlAbandon(run.id);await clearBattle(this.identity.id);this.stored=undefined;this.progress=await api.brawlProgress();this.lobby();}finally{this.busy=false;}}
    else if(id==='sound'){audio.setEnabled(!audio.enabled);button.textContent=audio.enabled?'♫':'♫ ×';button.setAttribute('aria-pressed',String(audio.enabled));if(audio.enabled)audio.brawl('pickup');}else if(id==='pause')this.pause();else if(id==='continue'){if(window.innerHeight>window.innerWidth){this.notice(this.t('請將裝置轉為橫向。','Please rotate to landscape.'));return;}this.input?.clear();this.root.querySelector('.brawl-modal')?.remove();if(!this.beginStory())this.paused=false;}
    else if(id==='retry'){this.advance(I.RETRY);this.paused=false;this.root.querySelector('.brawl-modal')?.remove();}
    else if(id==='finish-retry')void this.finish();else if(id==='lobby'){this.pause();await this.persist();this.progress=await api.brawlProgress();this.lobby();}
    else if(id==='end'){this.advance(I.END);void this.finish();}
    else if(id==='nextchapter'){const chapter=this.storyChapter(),next=chapter&&this.catalog.stages[chapter.number];if(next&&this.settled){this.adventureAct=next.act;this.lobby();await this.start(next.id);}}else if(id==='again'){if(this.online){this.mode=this.online.match.mode==='ranked'?'ranked':'pvp';this.online=undefined;this.pvp?.clearResult();await this.refreshRanking(false);}if(this.run&&!this.settled)return;this.stored=await loadBattle(this.identity.id).catch(()=>undefined);this.progress=await api.brawlProgress();this.lobby();}
    else if(id==='shop')this.shop();else if(id==='unlimited'){const unlimited=(button as HTMLButtonElement).getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(unlimited));button.classList.toggle('on',unlimited);}
  }
  private async start(stageId:string){const pet=this.bootstrap().pets.find(p=>p.speciesId===this.selected);if(!pet)throw new Error(this.t('請先購買這隻角色才可出戰。','Own this fighter before playing.'));await this.pvp?.reserveLocal();const difficulty=this.root.querySelector<HTMLSelectElement>('#brawlDifficulty')?.value||'easy',opponentId=this.root.querySelector<HTMLSelectElement>('#brawlOpponent')?.value||FIGHTERS[1].id;
    let options:BattleOptions={version:VERSION,fighterId:this.selected,stageId,difficulty,mode:this.mode,opponentId,seed:crypto.getRandomValues(new Uint32Array(1))[0]};this.run=undefined;
    if(this.mode==='campaign'){const pet=this.bootstrap().pets.find(p=>p.speciesId===this.selected);if(!pet)throw new Error(this.t('請選自己的寵物。','Choose a pet you own.'));const response=await api.brawlStart({petId:pet.id,stageId,difficulty},crypto.randomUUID());if(this.disposed)return;this.run=response.run;options=this.run.options;}
    if(this.mode!=='campaign')await api.brawlAccess({petId:pet.id,fighterId:this.selected,mode:this.mode});
    if(this.disposed)return;this.inputs=[];this.lastMask=0;this.finishKey=crypto.randomUUID();this.battle=createBattle(options);this.storyProgress={revision:STORY_REVISION,seen:[]};this.play(false);await this.persist();
  }
  private battleFighter(version:string,id:string){return version===VERSION?combatFighterById(id):fightersForVersion(version).find(f=>f.id===id);}
  private elementName(element:unknown){const names:Record<string,[string,string]>={fire:['🔥 火','🔥 Fire'],ice:['❄ 冰','❄ Ice'],lightning:['⚡ 雷','⚡ Lightning'],water:['≈ 水','≈ Water'],wind:['≋ 風','≋ Wind'],earth:['◆ 土','◆ Earth'],nature:['♧ 木','♧ Nature'],lunar:['☾ 月','☾ Moon'],light:['✦ 光','✦ Light'],ki:['✹ 氣','✹ Ki'],chakra:['◎ 螺旋','◎ Chakra'],psychic:['◉ 念','◉ Psychic'],physical:['● 拳壓','● Physical']};const label=names[String(element)];return label?this.t(...label):'';}
  private play(resume:boolean){this.stopScene();this.settled=false;this.finishing=false;this.ready=false;this.paused=true;this.root.className='brawl-layer brawl-battle';document.querySelector('.pet-shell')?.classList.add('brawl-active');const surface=document.querySelector<HTMLElement>('#playSurface')!;surface.style.backgroundImage='none';surface.style.backgroundColor='#102239';const s=this.battle!,local=s.actors[this.online?.playerIndex||0],f=this.battleFighter(s.version,local.kind)!;this.pvp?.setBusy(true);
    this.root.innerHTML=`<div class="brawl-hud"><div class="brawl-player-hud">${this.online?`<small class="pvp-player-name">${esc(this.online.match.players[this.online.playerIndex].name)}</small>`:''}<b>${esc(this.name(f.name))}</b><div class="brawl-meter hp"><i id="brawlHp"></i><span id="brawlHpText"></span></div><div class="brawl-meter mp"><i id="brawlMp"></i><span id="brawlMpText"></span></div><div class="brawl-meter guard"><i id="brawlGuard"></i></div></div><div class="brawl-objective">${s.mode==='campaign'?'<small id="brawlChapter" class="brawl-chapter-label"></small>':''}<b id="brawlWave"></b>${s.mode==='campaign'?'<div class="brawl-adventure-progress" aria-hidden="true"><i></i><i></i><i></i><i></i></div>':''}<small id="brawlTimer"></small><div id="brawlBoss"></div></div><div class="brawl-toolbar"><button data-brawl="sound" class="brawl-pause brawl-sound" aria-pressed="${audio.enabled}" aria-label="${this.t('切換音效','Toggle sound')}">${audio.enabled?'♫':'♫ ×'}</button><button data-brawl="pause" class="brawl-pause" aria-label="${this.t('暫停','Pause')}">Ⅱ</button></div></div>
      <div id="brawlHint" class="brawl-hint"></div><div class="brawl-controls"><div data-stick class="brawl-stick" aria-label="${this.t('移動搖桿','Movement joystick')}"><span>↕</span><div class="brawl-stick-knob"></div></div><div class="brawl-buttons"><div class="brawl-skill-buttons">${f.skills.map((k,n)=>`<button data-battle-key="${n===0?I.SKILL1:I.SKILL2}" class="brawl-skill" data-state="ready" data-element="${esc(String(k.element||'star'))}" aria-disabled="false" title="${esc(k.description?this.name(k.description):this.name(k.name))}"><small class="brawl-skill-key">${n===0?'U':'I'}</small><span class="brawl-skill-element">${esc(this.elementName(k.element)||'✦')}</span><span class="brawl-skill-cost" id="brawlCost${n}">${k.mp} MP</span><span class="brawl-skill-name">${esc(this.name(k.name))}</span><i id="brawlCooldown${n}" class="brawl-skill-status">${this.t('就緒','Ready')}</i><span class="brawl-skill-progress" aria-hidden="true"><span></span></span></button>`).join('')}</div><div class="brawl-basic-buttons"><button data-battle-key="${I.GUARD}">${this.t('防禦','Guard')}<small>L</small></button><button data-battle-key="${I.JUMP}">${this.t('跳躍','Jump')}<small>K</small></button><button data-battle-key="${I.ATTACK}" class="brawl-attack">${this.t('攻擊','Attack')}<small>J</small></button></div></div></div>
      <div class="brawl-keyboard-note">WASD / ↕↔ · J ${this.t('攻擊','attack')} · K ${this.t('跳躍','jump')} · L ${this.t('防禦','guard')} · U / I ${this.t('技能','skills')}</div>${s.mode==='practice'?`<button class="brawl-unlimited" data-brawl="unlimited" aria-pressed="false">${this.t('無限 MP','Unlimited MP')}</button>`:''}<div class="brawl-notice" role="status"></div><div class="brawl-loading">${this.t('正在準備戰場…','Preparing the arena…')}</div>`;
    this.releaseBrowserInteractions=lockGameBrowserInteractions('brawl-input-locked');
    this.input=new BattleInput(this.root,()=>!!this.battle&&this.ready&&!this.paused&&!this.accessLocked&&this.battle.status==='playing',()=>this.pause(),bit=>{if(bit!==I.SKILL1&&bit!==I.SKILL2)return true;const s=this.battle;if(!s)return false;const p=s.actors[this.online?.playerIndex||0],k=this.battleFighter(s.version,p.kind)?.skills[bit===I.SKILL1?0:1];return !!k&&skillState(p,k,bit===I.SKILL1?0:1,s.tick).available;});
    if(!this.game.scene.keys.Brawl)this.game.scene.add('Brawl',BattleScene,false);
    this.game.scene.start('Brawl',{state:s,playerId:local.id,assets:this.catalog.assets,locale:this.locale,paused:()=>this.paused||this.accessLocked,step:(mask?:number)=>this.advance(mask),changed:()=>this.updateHud(),loaded:()=>{if(this.disposed)return;this.ready=true;this.root.querySelector('.brawl-loading')?.remove();this.game.scale.refresh();audio.setTheme('brawl');if(!this.beginStory()){if(resume||window.innerHeight>window.innerWidth)this.pause();else this.paused=false;}if(this.online){void this.pvp?.ready().catch(e=>this.notice(e.message));this.networkStatus();return;}if(['won','lost','draw'].includes(s.status)&&!this.story)void this.finish();else if(s.status==='ko')this.showKo();},failed:()=>{if(this.online){void this.pvp?.leave().catch(e=>this.notice(e.message));return;}this.paused=true;this.root.querySelector('.brawl-loading')?.remove();this.modal(this.t('戰場素材未能載入','Arena assets could not load'),`<p>${this.t('進度已保留，請返回大廳重試。','Your progress is saved. Return to the lobby to retry.')}</p><button class="primary" data-brawl="lobby">${this.t('返回大廳','Back to lobby')}</button>`);}});
    if(this.online)this.networkTimer=window.setInterval(()=>this.networkStatus(),250);else this.timer=window.setInterval(()=>void this.persist(),5000);
  }
  advance(mask?:number){const s=this.battle;if(this.accessLocked||!s||this.disposed||this.settled||this.finishing||this.story||['won','lost','draw'].includes(s.status))return;if(this.online){this.pvp?.input(mask??this.input?.read()??0);return;}const value=mask??this.input?.read()??0;
    if(this.run&&value!==this.lastMask){this.inputs.push({tick:s.tick+1,mask:value});this.lastMask=value;}
    if(s.mode==='practice'&&this.root.querySelector('[data-brawl="unlimited"]')?.getAttribute('aria-pressed')==='true')s.actors[0].mp=10000;
    const previousZone=s.zone;stepBattle(s,value);(this.game.scene.getScene('Brawl') as BattleScene)?.receiveEvents(s.events,s.tick);if(s.zone!==previousZone){this.beginStory();void this.persist();}
    if(s.status==='ko'){this.paused=true;this.input?.clear();this.showKo();void this.persist();}else if(['won','lost','draw'].includes(s.status)){this.paused=true;this.input?.clear();void this.persist();window.setTimeout(()=>{if(!this.disposed&&this.battle===s&&!this.settled){if(s.status!=='won'||!this.beginStory())void this.finish();}},s.status==='won'?1400:400);}
  }
  private updateHud(){const s=this.battle;if(!s)return;const p=s.actors[this.online?.playerIndex||0],hp=this.root.querySelector<HTMLElement>('#brawlHp'),mp=this.root.querySelector<HTMLElement>('#brawlMp');if(!hp||!mp)return;hp.style.width=`${p.hp/p.maxHp*100}%`;mp.style.width=`${p.mp/100}%`;this.root.querySelector<HTMLElement>('#brawlGuard')!.style.width=`${p.guard/100}%`;this.root.querySelector('#brawlHpText')!.textContent=`${p.hp} / ${p.maxHp}`;this.root.querySelector('#brawlMpText')!.textContent=`MP ${Number((p.mp/100).toFixed(1))}`;
    this.root.querySelector('#brawlWave')!.textContent=this.online?.match.mode==='ranked'?this.t('排名對戰 · '+rankName(this.online.match.rankTier??0,this.locale),'Ranked duel · '+rankName(this.online.match.rankTier??0,this.locale)):s.mode==='campaign'?this.t(`第 ${s.zone+1} 節 / 4 · ${this.name(chapterByStage(s.stageId)!.sections[s.zone].title)}`,`${s.zone+1} / 4 · ${this.name(chapterByStage(s.stageId)!.sections[s.zone].title)}`):this.t({practice:'練習場',tutorial:'學習操作',duel:'AI 對戰',pvp:'同學對戰'}[s.mode as 'practice']||'冒險',{practice:'Practice',tutorial:'Learn',duel:'AI duel',pvp:'Live duel'}[s.mode as 'practice']||'Adventure');
    if(s.mode==='campaign'){this.root.querySelector('#brawlChapter')!.textContent=this.name(chapterByStage(s.stageId)!.title);this.root.querySelectorAll('.brawl-adventure-progress i').forEach((node,n)=>{node.classList.toggle('done',n<s.zone);node.classList.toggle('current',n===s.zone);});}
    const seconds=Math.floor(s.tick/60);this.root.querySelector('#brawlTimer')!.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;const boss=s.actors.find(a=>a.boss&&a.team===1&&!a.dummy);const opponent=this.online?s.actors[1-this.online.playerIndex]:s.mode==='duel'?s.actors.find(a=>a.team===1):boss;this.root.querySelector('#brawlBoss')!.innerHTML=opponent?`<div class="brawl-boss-name">${this.online?esc(this.online.match.players[1-this.online.playerIndex].name)+' · ':''}${boss?esc(this.name(STAGES.find(x=>x.id===s.stageId)!.bossName)):esc(this.name(this.battleFighter(s.version,opponent.kind)!.name))}</div><div class="brawl-boss-meter"><i style="width:${opponent.hp/opponent.maxHp*100}%"></i></div>`:'';
    const fighter=this.battleFighter(s.version,p.kind)!;const hints=[this.t('先移動：WASD 或左下搖桿','Move with WASD or the left joystick'),this.t('按住攻擊完成三連段；跑動時攻擊可衝擊','Hold attack for a three-hit combo; attack while running to charge'),this.t('跳躍能避開地面攻擊','Jump to evade ground attacks'),this.t('按住防禦，留意敵人朝向','Hold guard and face your enemy'),`${this.name(fighter.skills[0].name)} · U${fighter.skills[0].description?' · '+this.name(fighter.skills[0].description):''}`,`${this.name(fighter.skills[1].name)} · I${fighter.skills[1].description?' · '+this.name(fighter.skills[1].description):''}`];this.root.querySelector('#brawlHint')!.textContent=s.mode==='tutorial'?hints[s.lesson]||'':s.cleared&&s.zone<3?this.t('本節完成！向右走到下一節 →','Section clear! Move right to continue →'):s.mode==='campaign'?this.name(chapterByStage(s.stageId)!.sections[s.zone].objective):s.mode==='practice'&&s.version===VERSION&&p.kind==='starpatch-cat'?this.t('U 星影換位：繞背留下星印 · I 獵星連爪：躍起三連擊，消耗星印加強末擊','U Starstep: blink behind and mark · I Starhunt: leap for three claws; consume the mark for a stronger finisher'):s.mode==='practice'?this.t('跑動＋攻擊：衝刺重擊 · 跳躍＋攻擊：空中重擊 · 防禦→朝向→攻擊／跳躍：技能','Guard → forward → attack / jump also casts skills'):'';
    if(p.wardUntil>s.tick)this.root.querySelector('#brawlHint')!.textContent=this.t(`預知結界 ${((p.wardUntil-s.tick)/60).toFixed(1)}s · 近攻 ${p.wardMeleeLeft}/3 或遠攻 1 次`,`Ward ${((p.wardUntil-s.tick)/60).toFixed(1)}s · ${p.wardMeleeLeft}/3 melee or one ranged hit`);
    if(p.flightUntil>s.tick)this.root.querySelector('#brawlHint')!.textContent=this.t(`竹蜻蜓 ${((p.flightUntil-s.tick)/60).toFixed(1)}s · 剩餘射線 ${p.flightShots}/3`,`Take-copter ${((p.flightUntil-s.tick)/60).toFixed(1)}s · Rays ${p.flightShots}/3`);
    const peel=s.fields?.find((f:any)=>f.owner===p.id&&f.kind==='banana-prank'&&f.expires>s.tick);if(peel)this.root.querySelector('#brawlHint')!.textContent=this.t(`蕉皮等待中 ${((peel.expires-s.tick)/60).toFixed(1)}s · 踩中後滑倒`,`Peel ready ${((peel.expires-s.tick)/60).toFixed(1)}s · Trips the first enemy`);
    const dragonWard=s.fields?.find((f:any)=>f.owner===p.id&&f.mechanic==='weapon-ward'&&f.expires>s.tick);if(dragonWard)this.root.querySelector('#brawlHint')!.textContent=this.t(`銀龍護陣 ${((dragonWard.expires-s.tick)/60).toFixed(1)}s · 剩餘擋彈 ${dragonWard.blocksLeft}/2`,`Silver Dragon Ward ${((dragonWard.expires-s.tick)/60).toFixed(1)}s · Blocks ${dragonWard.blocksLeft}/2`);
    const attackButton=this.root.querySelector('.brawl-attack');if(attackButton?.firstChild)attackButton.firstChild.textContent=p.flightUntil>s.tick?this.t(`射線 ${p.flightShots}/3`,`Ray ${p.flightShots}/3`):this.t('攻擊','Attack');
    fighter.skills.forEach((k,n)=>{
      const button=this.root.querySelector<HTMLElement>(`[data-battle-key="${n===0?I.SKILL1:I.SKILL2}"]`),label=this.root.querySelector(`#brawlCooldown${n}`),cost=this.root.querySelector(`#brawlCost${n}`);if(!button||!label||!cost)return;
      const info=skillState(p,k,n,s.tick),text=info.state==='cooldown'?this.t(`冷卻 ${info.remaining.toFixed(1)}s`,`Wait ${info.remaining.toFixed(1)}s`):info.state==='mana'?this.t(`MP 不足 · 差 ${info.missingMana}`,`Need ${info.missingMana} MP`):info.state==='stunned'?this.t('暈眩中','Stunned'):info.state==='frozen'?this.t('冰封中','Frozen'):info.state==='shocked'?this.t('麻痺中','Shocked'):info.state==='air'?this.t('落地後使用','Land to cast'):info.state==='locked'?this.t('無法使用','Unavailable'):info.state==='busy'?this.t('動作中','In action'):this.t('就緒','Ready');
      button.dataset.state=info.state;button.setAttribute('aria-disabled',String(!info.available));button.setAttribute('aria-label',`${this.name(k.name)} · ${k.mp} MP · ${text}${info.missingMana&&info.state!=='mana'?this.t(` · MP 不足，差 ${info.missingMana}`,` · Need ${info.missingMana} MP`):''}`);button.style.setProperty('--cooldown',String(info.progress));label.textContent=text;cost.classList.toggle('short',info.missingMana>0);
    });
  }
  private storyChapter(){return this.battle?.mode==='campaign'?chapterByStage(this.battle.stageId):undefined;}
  private beginStory(){const chapter=this.storyChapter(),s=this.battle;if(!chapter||!s)return false;const scene=pendingStory(chapter,s,this.storyProgress);if(!scene)return false;const index=this.storyProgress.active?.id===scene.id?this.storyProgress.active.index:0;this.story={scene,index,chapter,review:false};this.paused=true;this.input?.clear();this.renderStory();void this.persist();return true;}
  private reviewStory(stageId:string,sceneId?:string){const chapter=chapterByStage(stageId);if(!chapter||!Object.keys(this.progress.best).some(k=>k.startsWith(stageId+':')))return;const scene=chapterScenes(chapter).find(s=>s.id===sceneId)||chapter.sections[0].scene;this.story={scene,index:0,chapter,review:true};this.renderStory();}
  private storyPortrait(speaker:string){
    const person=ADVENTURE.speakers[speaker],heroId=this.battle?.fighterId||this.selected;
    const fighterId=speaker==='hero'?heroId:person.fighterId,art=fighterId?this.bootstrap().catalog.pets.find(p=>p.id===fighterId)?.art[0]:undefined;
    const portrait=this.catalog.assets.storyPortraits?.[speaker];if(portrait)return `<div class="brawl-story-portrait"><img src="${esc(portrait)}" alt=""></div>`;
    if(art)return `<div class="brawl-story-portrait"><img src="${esc(art)}" alt=""></div>`;
    if(person.enemy){const sheet=this.catalog.assets.enemySprites?.[person.enemy],row=sheet?.row??this.catalog.assets.enemies.rows[person.enemy],url=sheet?.url??this.catalog.assets.enemies.url;return `<div class="brawl-story-portrait"><div class="brawl-story-enemy" style="--enemy-row:${row};--enemy-rows:${sheet?.rows||8};background-image:url('${esc(url)}');background-position:0 ${-row*144}px"></div></div>`;}
    return `<div class="brawl-story-portrait"><span class="brawl-story-symbol" aria-hidden="true">${person.symbol}</span></div>`;
  }
  private renderStory(){
    const story=this.story;if(!story)return;const {scene,index,chapter,review}=story,line=scene.lines[index],person=ADVENTURE.speakers[line.speaker],hero=this.name(this.battleFighter(this.battle?.version||VERSION,this.battle?.fighterId||this.selected)!.name);
    this.root.querySelector('.brawl-modal')?.remove();this.root.querySelector('.brawl-story-overlay')?.remove();
    if(!review)this.storyProgress.active={id:scene.id,index};
    const overlay=document.createElement('div');overlay.className='brawl-story-overlay';overlay.dataset.scene=scene.id;overlay.dataset.line=String(index);
    const last=index===scene.lines.length-1,sectionIndex=chapter.sections.findIndex(s=>s.scene.id===scene.id),end=scene.kind==='ending';
    const next=review?(last?this.t('返回大廳','Back to lobby'):this.t('下一段 →','Next →')):!last?this.t('下一段 →','Next →'):end?this.t(chapter.number===20?'完成冒險 ✦':'領取成果 ✦',chapter.number===20?'Finish adventure ✦':'Collect results ✦'):this.t(scene.kind==='boss'?'迎戰 Boss →':'開始這一節 →',scene.kind==='boss'?'Face the boss →':'Start section →');
    overlay.innerHTML=`<section class="brawl-story-panel" role="dialog" aria-modal="true" aria-labelledby="brawlStoryTitle" aria-describedby="brawlStoryLine" tabindex="-1"><header class="brawl-story-heading" style="background-image:url('${esc(this.catalog.assets.backgrounds[chapter.stageId])}')"><p>✦ ${esc(this.name(ADVENTURE.title))} ${review?' · '+this.t('故事回顧','Story review'):''}</p><h2 id="brawlStoryTitle">${esc(this.name(chapter.title))}</h2><small>${esc(this.name(scene.title))}</small><div class="brawl-story-section-rail">${chapter.sections.map((s,n)=>`<span class="${n===sectionIndex?'current':''}" ${n===sectionIndex?'aria-current="step"':''}><b>${n+1}</b>${esc(this.name(s.title))}</span>`).join('')}</div></header>${review?`<nav class="brawl-story-review-tabs" aria-label="${this.t('回顧段落','Review scenes')}">${chapterScenes(chapter).map((s,n)=>`<button data-brawl="story-review-scene" data-stage="${chapter.stageId}" data-scene="${s.id}" class="${s.id===scene.id?'selected':''}" aria-pressed="${s.id===scene.id}">${n===4?this.t('章節結局','Chapter ending'):`${n+1} · ${esc(this.name(chapter.sections[n].title))}`}</button>`).join('')}</nav>`:''}${sectionIndex>=0?`<p class="brawl-story-objective"><b>${this.t('本節目標','Your objective')}</b>${esc(this.name(chapter.sections[sectionIndex].objective))}</p>`:''}<div class="brawl-story-conversation">${this.storyPortrait(line.speaker)}<div><p class="brawl-story-speaker">${line.speaker==='hero'?esc(hero):esc(this.name(person.name))}</p><p id="brawlStoryLine" class="brawl-story-line" aria-live="polite" aria-atomic="true">${esc(storyText(line.text,this.locale,hero))}</p><p class="brawl-story-counter">${index+1} / ${scene.lines.length} · ${end?this.t('章節結局','Chapter ending'):this.t(`第 ${sectionIndex+1} 節 / 4`,`Section ${sectionIndex+1} / 4`)}</p></div></div><footer class="brawl-story-footer"><small class="brawl-story-help">${review?this.t('已完成章節可隨時重溫','Completed chapters can be revisited'):this.t('閱讀時戰鬥暫停 · Enter 下一段','Combat is paused · Enter to continue')}</small><button data-brawl="story-back" ${index===0?'disabled':''}>${this.t('上一段','Previous')}</button><button class="primary" data-brawl="story-next">${next}</button>${!review?`<button class="brawl-story-exit" data-brawl="lobby">${this.t('儲存並返回大廳','Save and return')}</button>`:''}</footer></section>`;
    this.root.append(overlay);this.setStoryBackground(true);overlay.querySelector<HTMLButtonElement>('[data-brawl="story-next"]')?.focus({preventScroll:true});this.updateHud();
  }
  private setStoryBackground(inert:boolean){for(const node of this.root.children)if(node instanceof HTMLElement&&!node.classList.contains('brawl-story-overlay'))node.inert=inert;}
  private closeStory(){this.root.querySelector('.brawl-story-overlay')?.remove();this.setStoryBackground(false);this.story=undefined;}
  private moveStory(back=false){
    const story=this.story;if(!story)return;
    if(back){story.index=Math.max(0,story.index-1);this.renderStory();if(!story.review)void this.persist();return;}
    if(story.index<story.scene.lines.length-1){story.index++;this.renderStory();if(!story.review)void this.persist();return;}
    if(story.review){this.closeStory();this.root.querySelector<HTMLButtonElement>(`[data-brawl="story-review"][data-stage="${story.chapter.stageId}"]`)?.focus();return;}
    if(window.innerHeight>window.innerWidth&&story.scene.kind!=='ending'){this.root.querySelector('.brawl-story-help')!.textContent=this.t('請將裝置轉為橫向，再開始戰鬥。','Rotate to landscape before starting combat.');return;}
    this.storyProgress.seen=[...new Set([...this.storyProgress.seen,story.scene.id])];delete this.storyProgress.active;this.closeStory();this.input?.clear();void this.persist();
    if(this.battle?.status==='won'){void this.finish();return;}
    this.paused=document.hidden;if(this.paused)this.pause();else this.updateHud();
  }
  private storyKeyboard(event:KeyboardEvent){
    if(this.accessLocked||!this.story)return;
    if(event.key==='Tab'){const buttons=[...this.root.querySelectorAll<HTMLButtonElement>('.brawl-story-overlay button:not(:disabled)')],first=buttons[0],last=buttons.at(-1);if((event.shiftKey&&document.activeElement===first)||(!event.shiftKey&&document.activeElement===last)){event.preventDefault();(event.shiftKey?last:first)?.focus();}return;}
    if(['Enter',' '].includes(event.key)&&event.target instanceof HTMLButtonElement){if(event.repeat)event.preventDefault();return;}
    if(['Enter',' ','Escape','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();event.stopImmediatePropagation();if(event.repeat)return;if(event.key==='Escape'){if(this.story.review)this.closeStory();return;}this.moveStory(event.key==='ArrowLeft');}
  }

  private modal(title:string,body:string){this.root.querySelector('.brawl-modal')?.remove();const element=document.createElement('div');element.className='brawl-modal';element.innerHTML=`<section role="dialog" aria-modal="true" aria-labelledby="brawlDialogTitle"><p class="brawl-eyebrow">PET BRAWL</p><h2 id="brawlDialogTitle">${esc(title)}</h2>${body}</section>`;this.root.append(element);element.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true});}
  pause(){if(this.story&&!this.story.review){this.paused=true;this.input?.clear();void this.persist();return;}if(this.online){if(this.disposed||!this.ready||this.settled||['finished','cancelled','settling'].includes(this.online.phase))return;this.paused=true;this.input?.clear();this.pvp?.input(0,true);this.modal(this.t('對戰仍在進行','The duel continues'),`<p class="pvp-pause-note">${['preparing','countdown'].includes(this.online.phase)?this.t('對戰準備中；開場前離開會退回雙方入場費。','Leaving before the duel starts refunds both entry fees.'):this.t('選單不會暫停對手。離開對戰會判負，入場費不退回。','This menu does not pause your opponent. Surrendering ends your duel without an entry refund.')}</p><button class="primary" data-brawl="continue">${this.t('繼續對戰','Continue duel')}</button><button class="secondary" data-brawl="pvp-leave">${this.t('投降並結束對戰','Surrender')}</button>`);return;}if(!this.battle||this.disposed||!this.ready||!['playing'].includes(this.battle.status))return;this.paused=true;this.input?.clear();this.modal(this.t('休息一下','Take a breather'),`<p>${this.t('進度已暫停。iPad 請使用橫向畫面。','Your adventure is paused. Use landscape on iPad.')}</p><div class="brawl-audio-settings"><label>${this.t('音樂','Music')}<input id="brawlMusic" type="range" min="0" max="1" step="0.05" value="${audio.musicLevel}"></label><label>${this.t('音效','Effects')}<input id="brawlSfx" type="range" min="0" max="1" step="0.05" value="${audio.sfxLevel}"></label></div><button class="primary" data-brawl="continue">${this.t('繼續冒險','Continue')}</button><button class="secondary" data-brawl="lobby">${this.t('儲存並返回大廳','Save and return')}</button>`);void this.persist();}
  private showKo(){this.modal(this.t('再試一次，你做得到！','You can do this!'),`<p>${this.t('可免費重試這一波一次，HP 和 MP 回滿。','Retry this wave once for free, with full HP and MP.')}</p><button class="primary" data-brawl="retry">${this.t('重試這一波','Retry wave')}</button><button class="secondary" data-brawl="end">${this.t('結束這次冒險','End adventure')}</button>`);}
  private async finish(){if(this.finishing||this.settled||!this.battle||this.story&&!this.story.review)return;this.finishing=true;this.paused=true;if(this.timer!==undefined)clearInterval(this.timer);this.timer=undefined;const s=this.battle;this.updateHud();this.modal(this.t('正在整理冒險成果…','Gathering your adventure results…'),`<p>${this.t('請稍候，正在確認本次結果。','Please wait while your result is checked.')}</p>`);
    try{let receipt:BrawlReceipt|undefined;if(this.run){await this.persist();const response=await api.brawlFinish(this.run.id,{version:s.version,inputs:this.inputs,endTick:s.tick},this.finishKey);receipt=response.receipt;this.settled=true;await this.saveQueue;await clearBattle(this.identity.id).catch(()=>{});this.stored=undefined;const synced=await Promise.allSettled([this.refresh(),api.brawlProgress()]);if(synced[1].status==='fulfilled')this.progress=synced[1].value;}
      if(this.disposed)return;this.settled=true;const result=receipt||battleResult(s),finalChapter=s.mode==='campaign'&&chapterByStage(s.stageId)!.number===ADVENTURE.chapters.length;audio.sfx(result.outcome==='won'?'win':'lose');this.modal(this.t(result.outcome==='won'?(s.mode==='campaign'?(finalChapter?'冒險完成！':'章節完成！'):'勝利！'):result.outcome==='draw'?'勢均力敵':'下次再挑戰！',result.outcome==='won'?(s.mode==='campaign'?(finalChapter?'Adventure complete!':'Chapter complete!'):'Victory!'):result.outcome==='draw'?'An even match':'Try again soon!'),`<div class="brawl-result-stars">${result.stars?'★'.repeat(result.stars)+'☆'.repeat(3-result.stars):result.outcome==='won'?'✦':'♡'}</div><p>${this.t('遊玩時間','Time')} ${result.seconds}s · ${this.t('波次重試','Retries')} ${result.retries}${result.bestCombo?` · ${this.t('最佳連擊','Best combo')} ${result.bestCombo}`:''}</p>${receipt?`<div class="brawl-result-rewards"><b>+${receipt.rewards.coins} ${this.t('金幣','coins')}</b><b>+${receipt.rewards.xp} XP</b></div><p>${this.t('今日剩餘獎勵次數','Rewarded wins remaining')}: ${receipt.rewardsRemaining}</p>`:`<p>${this.t('練習及 AI 對戰不發養成獎勵。','Practice and AI duels do not award raising rewards.')}</p>`}${s.mode==='campaign'&&result.outcome==='won'&&chapterByStage(s.stageId)!.number<20?`<button class="primary" data-brawl="nextchapter">${this.t('前往下一章 →','Next chapter →')}</button>`:''}<button class="primary" data-brawl="again">${this.t('返回大廳','Back to lobby')}</button>`);
    }catch(error){if(!this.disposed)this.modal(this.t('成果仍在本頁，請重試','Your result is here. Please retry.'),`<p>${esc((error as Error).message)}</p><button class="primary" data-brawl="finish-retry">${this.t('重試結算','Retry settlement')}</button><button class="secondary" data-brawl="lobby">${this.t('返回大廳','Back to lobby')}</button>`);}finally{this.finishing=false;}
  }
  private persist(){if(!this.run||!this.battle||this.settled)return Promise.resolve();const stored:StoredBattle={version:this.battle.version,studentId:this.identity.id,run:this.run,inputs:this.inputs.map(f=>({...f})),endTick:this.battle.tick,updatedAt:Date.now(),finishKey:this.finishKey,story:structuredClone(this.storyProgress)};this.stored=stored;const pending=this.saveQueue.then(()=>saveBattle(stored));this.saveQueue=pending.catch(()=>{if(!this.disposed)this.notice(this.t('存檔未完成，請保持頁面開啟並稍後重試。','Saving failed. Keep this page open and try again.'));});return this.saveQueue;}
  private notice(message:string){const target=this.root.querySelector('.brawl-notice');if(target)target.textContent=message;}
  private stopScene(){this.closeStory();clearInterval(this.networkTimer);this.networkTimer=undefined;this.input?.destroy();this.input=undefined;this.releaseBrowserInteractions?.();this.releaseBrowserInteractions=undefined;if(this.timer!==undefined)clearInterval(this.timer);this.timer=undefined;if(this.game.scene.keys.Brawl)this.game.scene.stop('Brawl');}
  destroy(){if(this.disposed)return;void this.persist().catch(()=>{});this.disposed=true;this.abort.abort();this.stopScene();this.root.remove();document.querySelector('.pet-shell')?.classList.remove('brawl-active','brawl-open');}
}
