import './pvp.css';
import {FIGHTERS,STAGES} from '../../lib/brawl/catalog.mjs';
import type {BattleState} from '../../lib/brawl/simulation.mjs';
import type {Identity} from '../types';
import type {RankProfile,RankResult,RankedTerms} from './ranking-types';
import {rankBadge,rankTermsText} from './ranking-ui';
interface Socket {connected:boolean;connect():void;on(event:string,fn:(payload?:any)=>void):void;emit(event:string,payload:any,ack?:(result:any)=>void):void;disconnect():void}
export interface OnlinePeer {rankTerms?:RankedTerms;id:string;name:string;className:string;available:boolean;hasFighter:boolean;rank:RankProfile}
export interface DuelInvitation {rankTerms?:RankedTerms;id:string;mode?:'friendly'|'ranked';rankTier?:number;from:{id:string;name:string;className:string;fighterId:string};to:{id:string;name:string};petId:string;stageId:string;status:string;fee:number;expiresAt:number;message?:string;matchId?:string}
export interface DuelMatch {rankTerms?:RankedTerms;id:string;mode?:'friendly'|'ranked';rankTier?:number;rankResults?:RankResult[];players:{id:string;name:string;petId:string;fighterId:string}[];stageId:string;fee:number;status:string;version:string;reason?:string;winnerIndex?:number|null;refunded?:boolean}
export interface DuelSession {match:DuelMatch;playerIndex:number;phase:string;startAt:number;state:BattleState}
export interface DuelFrame {matchId:string;frameSeq:number;phase:string;startAt:number;reconnectUntil:number;state:BattleState;events:any[]}
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let clientScript:Promise<void>|undefined;
function loadClient(){return clientScript??=new Promise<void>((resolve,reject)=>{if((window as any).io){resolve();return;}const script=document.createElement('script');script.src='/socket.io/socket.io.js';script.async=true;script.onload=()=>resolve();script.onerror=()=>{clientScript=undefined;script.remove();reject(new Error('未能連接同學對戰。'));};document.head.append(script);});}
export class PvPClient extends EventTarget {
  private accessLocked=false;
  setAccessLocked(locked:boolean){this.accessLocked=locked;this.input(0,true);this.notifications.inert=locked;this.notifications.hidden=locked;if(!locked&&!this.connected)void this.start();void this.ping().catch(()=>{});}
  peers:OnlinePeer[]=[];invitation?:DuelInvitation;session?:DuelSession;connected=false;
  self?:{balance:number;pets:{petId:string;fighterId:string}[];rank:RankProfile};
  private socket?:Socket;private starting=false;private completed=new Set<string>();private busy=false;private active=!document.hidden;private closed=false;private abort=new AbortController();private notifications:HTMLElement;private heartbeat?:number;private invitationClock?:number;private lastMask=0;private lastSent=0;private sequence=0;private lastFrame=-1;private accepting=false;private selectedPet='';private lastNotice='';private needsResume=false;
  constructor(private identity:Identity){super();this.notifications=document.createElement('div');this.notifications.id='pvp-notifications';this.notifications.className='pvp-notifications';document.body.append(this.notifications);const signal=this.abort.signal;
    document.addEventListener('visibilitychange',()=>{this.active=!document.hidden;if(!this.active)this.input(0,true);void this.ping();},{signal});window.addEventListener('blur',()=>this.input(0,true),{signal});window.addEventListener('pagehide',event=>{if(event.persisted){this.active=false;this.input(0,true);void this.ping();}else this.destroy();},{signal});window.addEventListener('pageshow',event=>{if(event.persisted){this.active=!document.hidden;void this.start();void this.ping(true);}},{signal});
    this.notifications.addEventListener('change',event=>{const e=event.target as HTMLSelectElement;if(e.matches('[data-duel-pet]'))this.selectedPet=e.value;},{signal});
    this.notifications.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-duel-action]');if(!button)return;void this.notificationAction(button.dataset.duelAction!).catch(e=>this.notify(e.message));},{signal});
  }
  t(zh:string,en:string){return this.identity.language==='en-US'?en:zh;}
  async start(){if(this.closed||this.starting)return;if(this.socket){this.socket.connect();return;}this.starting=true;try{await loadClient();if(this.closed)return;this.socket=(window as any).io('/pet-brawl',{withCredentials:true,transports:['websocket','polling']});
    this.socket!.on('connect',()=>{this.connected=true;this.sequence=0;this.lastMask=0;this.lastFrame=-1;this.needsResume=true;void this.ping(true).catch(e=>this.notify(e.message));this.change();});
    this.socket!.on('disconnect',()=>{this.connected=false;this.change();});
    this.socket!.on('connect_error',error=>{if(error?.data?.access)window.dispatchEvent(new CustomEvent('pet:access',{detail:error.data.access}));this.connected=false;this.change();});
    this.socket!.on('pet:access',access=>window.dispatchEvent(new CustomEvent('pet:access',{detail:access})));
    this.socket!.on('duel:peers',data=>{this.peers=data.peers;this.change();});
    this.socket!.on('duel:invitation',inv=>this.receiveInvitation(inv));
    this.socket!.on('duel:match',session=>this.receiveMatch(session));
    this.socket!.on('duel:frame',frame=>{if(!this.session||frame.matchId!==this.session.match.id||frame.frameSeq<=this.lastFrame)return;this.lastFrame=frame.frameSeq;this.session.phase=frame.phase;this.session.startAt=frame.startAt;this.session.state=frame.state;this.dispatchEvent(new CustomEvent<DuelFrame>('frame',{detail:frame}));});
    this.socket!.on('duel:result',result=>this.receiveResult(result));
    this.socket!.on('duel:ranking-changed',()=>{void this.ping(true).then(()=>this.dispatchEvent(new Event('wallet'))).catch(()=>{});});
    this.heartbeat=window.setInterval(()=>void this.ping().catch(()=>{}),10000);this.invitationClock=window.setInterval(()=>{if(this.invitation?.status==='pending'){const timer=this.notifications.querySelector('[data-duel-countdown]');if(timer)timer.textContent=String(Math.max(0,Math.ceil((this.invitation.expiresAt-Date.now())/1000)));}},1000);
  }catch{this.connected=false;this.change();}finally{this.starting=false;}}
  private change(){this.dispatchEvent(new Event('change'));}
  private request<T=any>(event:string,payload:any):Promise<T>{return new Promise((resolve,reject)=>{if(!this.socket?.connected){reject(new Error(this.t('連線中，請稍後再試。','Connecting. Please try again shortly.')));return;}const timeout=window.setTimeout(()=>reject(new Error(this.t('回覆較慢，請稍後重試。','The reply is taking longer. Please retry.'))),12000);this.socket.emit(event,payload,(data:any)=>{clearTimeout(timeout);if(data.success===false){if(data.access)window.dispatchEvent(new CustomEvent('pet:access',{detail:data.access}));reject(new Error(data.message));}else resolve(data);});});}
  async ping(refresh=false){if(!this.socket?.connected||this.closed)return;const activeMatch=this.session&&!['finished','cancelled'].includes(this.session.phase)?this.session.match.id:null;const data=await this.request('duel:presence',{active:this.active&&!this.accessLocked,busy:this.busy,refresh,matchId:activeMatch||sessionStorage.getItem('pet-live-duel:'+this.identity.id)});this.peers=data.peers;const walletChanged=this.self&&JSON.stringify(this.self)!==JSON.stringify(data.self);this.self=data.self;if(walletChanged&&data.invitation)this.notifications.querySelector('.pvp-invite-card')?.remove();if(data.invitation)this.receiveInvitation(data.invitation);if(data.session)this.receiveMatch(data.session);if(data.result)this.receiveResult(data.result);this.change();}
  setBusy(busy:boolean){if(this.busy===busy)return;this.busy=busy;void this.ping().catch(()=>{});}
  async reserveLocal(){if(this.session&&!['finished','cancelled'].includes(this.session.phase))throw new Error(this.t('請先完成同學對戰。','Finish your live duel first.'));if(this.invitation?.status==='pending'){if(this.invitation.from.id===this.identity.id)await this.cancel();else await this.reply(false);}this.setBusy(true);await this.ping();}
  async invite(targetId:string,petId:string,stageId:string,key:string,mode:'friendly'|'ranked'='friendly'){const response=await this.request('duel:invite',{targetId,petId,stageId,key,mode});this.receiveInvitation(response.invitation);return response.invitation as DuelInvitation;}
  async cancel(){if(this.invitation)await this.request('duel:cancel',{inviteId:this.invitation.id});}
  async reply(accept:boolean,petId?:string){if(!this.invitation)return;const response=await this.request('duel:reply',{inviteId:this.invitation.id,accept,petId});if(response.invitation)this.receiveInvitation(response.invitation);if(response.session)this.receiveMatch(response.session);}
  private receiveInvitation(inv:DuelInvitation){this.invitation=inv;this.change();if(inv.status==='pending'){this.renderInvitation();return;}this.notifications.querySelector('.pvp-invite-card')?.remove();if(inv.status!=='accepted'&&inv.status!=='accepting')this.notify(inv.message||this.t('邀請已結束，雙方均未扣款。','Invitation closed. Neither student was charged.'));}
  private receiveMatch(session:DuelSession){if(this.completed.has(session.match.id))return;const old=this.session?.match.id;this.session=session;sessionStorage.setItem('pet-live-duel:'+this.identity.id,session.match.id);if(old!==session.match.id){this.lastFrame=-1;this.sequence=0;this.lastMask=0;}this.notifications.querySelector('.pvp-invite-card')?.remove();if(old!==session.match.id||this.needsResume){this.needsResume=false;this.dispatchEvent(new CustomEvent<DuelSession>('match',{detail:session}));}this.change();}
  private receiveResult(result:any){if(this.completed.has(result.match.id))return;this.completed.add(result.match.id);if(this.completed.size>64)this.completed.delete(this.completed.values().next().value!);sessionStorage.removeItem('pet-live-duel:'+this.identity.id);if(this.session&&result.match.id===this.session.match.id){this.session.match=result.match;this.session.phase=result.match.status;}else if(result.refunded)this.notify(this.t(`上次對戰已中斷，${result.match.fee} 金幣入場費已退回。`,`Your interrupted duel entry fee of ${result.match.fee} coins was refunded.`));const rank=result.match.rankResults?.find((r:RankResult)=>r.studentId===this.identity.id);if(rank&&this.self)this.self.rank=rank;this.dispatchEvent(new CustomEvent('result',{detail:result}));this.change();void this.ping(true).catch(()=>{});}
  async ready(){if(!this.session)return;const response=await this.request('duel:ready',{matchId:this.session.match.id});this.session=response.session;this.change();}
  input(mask:number,force=false){if(this.accessLocked)mask=0;if(!this.socket?.connected||!this.session||!['playing','countdown'].includes(this.session.phase))return;const time=performance.now();if(!force&&mask===this.lastMask&&time-this.lastSent<100)return;this.lastMask=mask;this.lastSent=time;this.socket.emit('duel:input',{matchId:this.session.match.id,seq:++this.sequence,mask:mask&1023});}
  async leave(){if(this.session)await this.request('duel:leave',{matchId:this.session.match.id});}
  clearResult(){sessionStorage.removeItem('pet-live-duel:'+this.identity.id);this.session=undefined;this.invitation=undefined;this.lastFrame=-1;this.setBusy(false);void this.ping(true).catch(()=>{});}
  private renderInvitation(){const inv=this.invitation!;if(inv.status!=='pending')return;const incoming=inv.to.id===this.identity.id,pets=this.self?.pets||[],locale=this.identity.language||'zh-HK';if(!pets.some(p=>p.petId===this.selectedPet))this.selectedPet=pets[0]?.petId||'';
    const current=this.notifications.querySelector('.pvp-invite-card');if(current?.getAttribute('data-invite-id')===inv.id)return;current?.remove();
    const card=document.createElement('section');card.className='pvp-invite-card';card.setAttribute('data-invite-id',inv.id);card.setAttribute('role',incoming?'alertdialog':'status');card.setAttribute('aria-labelledby','duelInviteTitle');
    card.innerHTML=`<p class="pvp-eyebrow">PET BRAWL · ${inv.mode==='ranked'?this.t('排名對戰','RANKED DUEL'):this.t('自由對戰','FREE DUEL')}</p><h2 id="duelInviteTitle">${incoming?(inv.mode==='ranked'?this.t('收到排名對戰邀請','Ranked duel invitation'):this.t('收到對戰邀請','Duel invitation')):this.t('等待同學回覆','Waiting for a reply')}</h2>${inv.mode==='ranked'?`<p>${inv.rankTerms?`${rankBadge(inv.rankTerms.tiers[0],locale)} vs ${rankBadge(inv.rankTerms.tiers[1],locale)}<br>${rankTermsText(inv.rankTerms,incoming?1:0,locale)}`:rankBadge(inv.rankTier??0,locale)} · ${this.t('正式計入排名；開場後投降會判負。','Counts toward rankings; surrender after starting is a loss.')}</p>`:''}<p><b>${esc(incoming?inv.from.name:inv.to.name)}</b> · ${esc(STAGES.find(s=>s.id===inv.stageId)?.name[locale])}</p><p>${this.t('接受邀請後，雙方各支付','Once accepted, each student pays')} <strong>${inv.fee} ${this.t('金幣','coins')}</strong>。${this.t('拒絕或逾時不扣款。','Declining or expiry costs nothing.')}</p><small>${this.t('剩餘','Remaining')} <span data-duel-countdown>${Math.max(0,Math.ceil((inv.expiresAt-Date.now())/1000))}</span>s</small>
      ${incoming?`<label>${this.t('你的出戰寵物','Your fighter')}<select data-duel-pet>${pets.map(p=>`<option value="${esc(p.petId)}" ${p.petId===this.selectedPet?'selected':''}>${esc(FIGHTERS.find(f=>f.id===p.fighterId)?.name[locale])}</option>`).join('')}</select></label><div class="pvp-invite-actions"><button data-duel-action="reject" class="secondary">${this.t('拒絕','Decline')}</button><button data-duel-action="accept" class="primary" ${!pets.length||(this.self?.balance||0)<inv.fee?'disabled':''}>${this.t(`接受 · 支付 ${inv.fee}`,`Accept · pay ${inv.fee}`)}</button></div>${(this.self?.balance||0)<inv.fee?`<p class="pvp-small">${this.t(`你的餘額不足 ${inv.fee} 金幣。`,`You need at least ${inv.fee} coins.`)}</p>`:''}`:`<button data-duel-action="cancel" class="secondary">${this.t('取消邀請','Cancel invitation')}</button>`}`;
    this.notifications.append(card);if(incoming)card.querySelector<HTMLButtonElement>('[data-duel-action="reject"]')?.focus({preventScroll:true});
  }
  private async notificationAction(action:string){if(this.accepting)return;if(action==='accept'&&innerHeight>innerWidth)throw new Error(this.t('請先將裝置轉為橫向，再接受對戰。','Rotate to landscape before accepting.'));this.accepting=true;this.notifications.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);try{if(action==='accept')await this.reply(true,this.selectedPet);else if(action==='reject')await this.reply(false);else if(action==='cancel')await this.cancel();}finally{this.accepting=false;if(this.invitation?.status==='pending'){this.notifications.querySelector('.pvp-invite-card')?.remove();this.renderInvitation();}}}
  notify(message:string){if(message===this.lastNotice)return;this.lastNotice=message;const notice=document.createElement('div');notice.className='pvp-notice';notice.setAttribute('role','status');notice.textContent=message;this.notifications.append(notice);window.setTimeout(()=>{notice.remove();if(this.lastNotice===message)this.lastNotice='';},6000);}
  destroy(){if(this.closed)return;this.closed=true;this.socket?.disconnect();clearInterval(this.heartbeat);clearInterval(this.invitationClock);this.abort.abort();this.notifications.remove();}
}
