import './ranking.css';
import type { Locale } from '../types';
import type { RankedOverview } from './ranking-types';
import { rankBadge } from './rank-display';
export { rankBadge, rankName, rankTermsText } from './rank-display';
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function rankSummary(data: RankedOverview | undefined, locale: Locale) {
  const zh = locale === 'zh-HK', t = (z: string, e: string) => zh ? z : e;
  if (!data) return `<section class="rank-summary rank-error"><h2>${t('排名資料暫未載入', 'Rankings could not load')}</h2><button data-brawl="rank-refresh">${t('重新載入排名', 'Reload rankings')}</button></section>`;
  const p = data.self, next = data.tiers[p.tier + 1];
  const progress = p.pointsToPromote ? `${p.points} / ${p.pointsToPromote} ${t('分', 'points')}` : `${p.points} ${t('分', 'points')}`;
  return `<section class="rank-summary" aria-label="${t('我的排名', 'My ranking')}">
    <div class="rank-summary-head"><div><p class="brawl-eyebrow">RANKED ARENA</p><h2>${t('一步一步，登上巔峰', 'Every point takes you higher')}</h2></div>${rankBadge(p.tier, locale)}</div>
    <div class="rank-stats"><span><b>${data.position ? `#${data.position}` : '—'}</b><small>${t('全校排名', 'School rank')}</small></span><span><b>${p.wins}</b><small>${t('排名勝場', 'Ranked wins')}</small></span><span><b>${p.games}</b><small>${t('遊玩場次', 'Matches played')}</small></span><span><b>${p.games ? `${p.winRate}%` : '—'}</b><small>${t('勝率', 'Win rate')}</small></span></div>
    <div class="rank-progress-head"><b>${next ? t(`再獲 ${p.pointsToPromote! - p.points} 分，升到${next.names['zh-HK']}`, `${p.pointsToPromote! - p.points} more points to ${next.names['en-US']}`) : t('鑽級挑戰繼續！', 'Keep competing in Diamond!')}</b><span>${progress}</span></div>
    ${p.pointsToPromote ? `<div class="rank-progress" role="progressbar" aria-label="${t('晉級積分進度', 'Promotion points')}" aria-valuemin="0" aria-valuemax="${p.pointsToPromote}" aria-valuenow="${p.points}"><i style="width:${p.points / p.pointsToPromote * 100}%"></i></div>` : ''}
    <div class="rank-benefit"><span aria-hidden="true">🪙</span><div><b>${p.dailyCoins ? t(`每日自動獲得 ${p.dailyCoins} 金幣`, `${p.dailyCoins} automatic coins daily`) : t('升到銅級，開始領取每日金幣', 'Reach Bronze to unlock daily coins')}</b><small>${p.dailyCoins ? p.rewardDay === data.day && p.rewardPaid >= p.dailyCoins ? t('今日已自動入帳 · 離線期間也會補發', 'Today’s coins are credited · offline days are included') : t('每日按香港時間自動入帳', 'Credited daily using Hong Kong time') : t('排名對戰勝利加分、落敗扣分 · 最低 0 分、不降級', 'Ranked wins add points; losses deduct points · minimum 0, no demotion')}</small></div></div>
    <div class="rank-summary-actions"><button data-brawl="mode" data-id="leaderboard">${t('全校排行榜 →', 'School leaderboard →')}</button><button data-brawl="rank-refresh">${t('更新排名', 'Refresh')}</button></div>
  </section>`;
}
export function rankLeaderboard(data: RankedOverview | undefined, locale: Locale, expanded = false) {
  const zh = locale === 'zh-HK', t = (z: string, e: string) => zh ? z : e;
  const rows = data?.leaderboard.slice(0, expanded ? undefined : 10) || [];
  return `${rankSummary(data, locale)}<section class="rank-board"><div class="rank-board-head"><div><p class="brawl-eyebrow">SCHOOL LEADERBOARD</p><h2>${t('全校排行榜', 'School leaderboard')}</h2><p>${t('按級別、積分、總勝場及勝率排列；只計排名對戰。', 'Ordered by tier, points, total wins and win rate. Ranked matches only.')}</p></div><button data-brawl="mode" data-id="ranked">${t('參加排名對戰', 'Play ranked')}</button></div>
    ${data ? `<div id="rankTable" class="rank-table-scroll" tabindex="0" aria-label="${t('全校排名表，可橫向捲動', 'School rankings, scroll horizontally')}" role="region"><table class="rank-table"><thead><tr>${[t('名次', 'Rank'), t('同學', 'Student'), t('級別', 'Tier'), t('積分', 'Points'), t('勝場', 'Wins'), t('勝率', 'Win rate'), t('遊玩場次', 'Played')].map(label => `<th scope="col">${label}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr class="${row.studentId === data.self.studentId ? 'rank-self' : ''}" data-rank-student="${esc(row.studentId)}"><td><b>${row.position <= 3 ? ['🥇', '🥈', '🥉'][row.position - 1] : row.position}</b></td><th scope="row"><b>${esc(row.name)}${row.studentId === data.self.studentId ? ` <small class="rank-you">${t('你', 'You')}</small>` : ''}</b><small>${esc(row.className)}</small></th><td>${rankBadge(row.tier, locale)}</td><td>${row.points}</td><td>${row.wins}</td><td>${row.games ? `${row.winRate}%` : '—'}</td><td>${row.games}</td></tr>`).join('')}</tbody></table></div>${data.leaderboard.length > 10 ? `<div class="rank-board-actions"><small>${t(`顯示 ${rows.length} / ${data.leaderboard.length} 名`, `Showing ${rows.length} / ${data.leaderboard.length} students`)}</small><button data-brawl="rank-expand" aria-controls="rankTable" aria-expanded="${expanded}">${expanded ? t('收起 · 只看首 10 名', 'Collapse · top 10') : t('展開全校排行榜', 'Show all students')}</button></div>` : ''}<p class="rank-board-note">${t('勝率＝勝場 ÷ 遊玩場次；平局不加減分，取消或退款的場次不計。', 'Win rate = wins ÷ matches played. Draws do not change points; cancelled or refunded matches do not.')}</p>` : ''}
  </section><section class="rank-roadmap" aria-label="${t('級別及獎勵', 'Tiers and rewards')}">${data?.tiers.map((tier, index) => `<article>${rankBadge(index, locale)}<b>${tier.dailyCoins ? `🪙 ${tier.dailyCoins} / ${t('日', 'day')}` : t('尚未有每日獎勵', 'No daily coins yet')}</b><small>${tier.pointsToPromote ? t(`此級別累積 ${tier.pointsToPromote} 分可晉級`, `${tier.pointsToPromote} points here to promote`) : t('最高級別', 'Highest tier')}</small></article>`).join('') || ''}</section>`;
}
