import type {StoryProgress} from '../../lib/brawl/story.mjs';
import type {Fighter,Stage} from '../../lib/brawl/catalog.mjs';
import type {BattleOptions,BattleResult,InputFrame} from '../../lib/brawl/simulation.mjs';
export interface BrawlAssets {skillFx?:Record<string,{url:string;frameWidth:number;frameHeight:number;frames:number;widthRatio:number;heightRatio?:number;originX:number;originY?:number;anchor?:string}>;fighters:Record<string,{pages:string[];pageLayouts?:Record<number,{frameWidth:number;frameHeight:number}>;frameWidth?:number;frameHeight?:number;originY?:number;runtime?:'pet';clips:Record<string,{page:number;start:number;count:number;frames?:number[];durations?:number[];emitters?:{x:number;y:number}[];poseTimeline?:'cast';displaySize?:number;originY?:number;emitterRole?:string}>}>;enemies:{url:string;rows:Record<string,number>};backgrounds:Record<string,string>;worlds?:Record<string,string>;areas?:Record<string,string[]>;enemySprites?:Record<string,{url:string;row:number;rows?:number;frames:number}>;storyPortraits?:Record<string,string>;effects?:{url:string;frameSize:number;clips:Record<string,{start:number;count:number}>};elementalFx?:{url:string;frameSize:number;frames:Record<string,number>};frameSize:number}
export interface BrawlCatalog {enabled:boolean;version:string;fighters:Fighter[];stages:Stage[];assets:BrawlAssets}
export interface BrawlRun {id:string;petId:string;options:BattleOptions;createdAt:string;expiresAt:string;status:string}
export interface BrawlProgress {day:string;best:Record<string,{stars:number;seconds:number;clears:number}>;rewardsRemaining:number;activeRun:BrawlRun|null}
export interface BrawlReceipt extends BattleResult {runId:string;rewards:{coins:number;xp:number};rewardsRemaining:number;day:string}
export interface StoredBattle {version:string;studentId:string;run:BrawlRun;inputs:InputFrame[];endTick:number;updatedAt:number;finishKey:string;story?:StoryProgress}
